"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { ArrowLeft, LockKeyhole, Save } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

export default function MonetizationAdminPage(){
 const s=createClient(); const [rows,setRows]=useState<any[]>([]); const [allowed,setAllowed]=useState(false); const [loading,setLoading]=useState(true); const [message,setMessage]=useState("");
 useEffect(()=>{(async()=>{const {data:{user}}=await s.auth.getUser();if(!user){location.href="/login?next=/admin/monetization";return}const {data:admin}=await s.rpc("is_super_admin",{check_user_id:user.id});if(!admin){setLoading(false);return}setAllowed(true);const {data,error}=await s.from("monetization_settings").select("id,setting_key,value,description,is_active,effective_at").order("setting_key");if(error)setMessage(error.message);setRows(data||[]);setLoading(false)})()},[]);
 async function save(row:any){setMessage("");const {error}=await s.from("monetization_settings").update({value:row.value,is_active:row.is_active,effective_at:row.effective_at||null,updated_at:new Date().toISOString()}).eq("id",row.id);setMessage(error?error.message:`Saved ${row.setting_key}.`)}
 if(loading)return <main className="mx-auto max-w-6xl px-4 py-8"><p>Loading…</p></main>;
 if(!allowed)return <main className="mx-auto max-w-xl px-4 py-16 text-center"><LockKeyhole size={42} className="mx-auto"/><h1 className="mt-4 text-2xl font-semibold">Access restricted</h1><p className="mt-2 text-sm text-[var(--muted)]">Only authorized administrators can change monetization settings.</p></main>;
 return <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8"><Link href="/admin" className="inline-flex items-center gap-2 text-sm text-[var(--muted)]"><ArrowLeft size={16}/> Admin</Link><header className="mt-5 rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-6 sm:p-8"><p className="text-xs font-semibold uppercase tracking-widest text-[var(--muted)]">Super Admin</p><h1 className="mt-1 text-3xl font-semibold">Monetization Configuration</h1><p className="mt-2 text-sm text-[var(--muted)]">One configuration layer for referral rewards, commission holding periods, withdrawal minimums and role-switch pricing. Financial calculations remain server-authoritative.</p></header>{message&&<p className="mt-4 text-sm text-[var(--muted)]">{message}</p>}<section className="mt-6 space-y-4">{rows.map((r,i)=><article key={r.id} className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><p className="font-semibold">{r.setting_key}</p><p className="mt-1 text-sm text-[var(--muted)]">{r.description||"Monetization setting"}</p></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!r.is_active} onChange={e=>setRows(x=>x.map((v,j)=>j===i?{...v,is_active:e.target.checked}:v))}/> Active</label></div><textarea value={JSON.stringify(r.value,null,2)} onChange={e=>{try{const value=JSON.parse(e.target.value);setRows(x=>x.map((v,j)=>j===i?{...v,value}:v))}catch{}}} className="mt-4 min-h-28 w-full rounded-xl border border-[var(--border)] bg-[var(--background)] p-3 font-mono text-xs"/><button onClick={()=>save(r)} className="mt-3 inline-flex items-center gap-2 rounded-xl border border-[var(--border)] px-4 py-2.5 text-sm font-semibold"><Save size={16}/> Save setting</button></article>)}</section></main>;
}
