"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, CheckCircle2, ExternalLink, MessageCircle, Package, Store, UserRound } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type StoreInfo={id:string;public_id:string|null;name:string;slug:string|null;description:string|null;logo_url:string|null;is_verified:boolean|null;verification_badge:boolean|null;owner_user_id:string|null};
type Listing={id:string;title:string;description:string|null;item_type:string|null;price:number|null;currency_code:string|null;created_at:string|null};

export default function PublicStorePage(){
 const params=useParamsId(); const id=params.id; const supabase=createClient();
 const [store,setStore]=useState<StoreInfo|null>(null); const [items,setItems]=useState<Listing[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 useEffect(()=>{if(!id)return;(async()=>{setLoading(true);setError("");const s=await supabase.from("stores").select("id,public_id,name,slug,description,logo_url,is_verified,verification_badge,owner_user_id").eq("id",id).maybeSingle();if(s.error){setError(s.error.message);setLoading(false);return}if(!s.data){setLoading(false);return}setStore(s.data as StoreInfo);const q=await supabase.from("marketplace_items").select("id,title,description,item_type,price,currency_code,created_at").eq("store_id",id).eq("status","published").order("created_at",{ascending:false});if(q.error)setError(q.error.message);else setItems((q.data||[]) as Listing[]);setLoading(false)})()},[id]);
 if(loading)return <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8"><div className="h-56 animate-pulse rounded-[2rem] border border-[var(--border)] bg-[var(--surface)]"/><div className="mt-6 h-64 animate-pulse rounded-[2rem] border border-[var(--border)] bg-[var(--surface)]"/></main>;
 if(error||!store)return <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8"><Link href="/marketplace" className="inline-flex items-center gap-2 text-sm text-[var(--muted)]"><ArrowLeft size={16}/> Marketplace</Link><div className="mt-6 rounded-[2rem] border border-dashed border-[var(--border)] bg-[var(--surface)] p-12 text-center"><Store className="mx-auto" size={30}/><h1 className="mt-4 text-xl font-semibold">Store not available</h1><p className="mt-2 text-sm text-[var(--muted)]">{error||"This store may be unavailable or not publicly visible."}</p></div></main>;
 const verified=Boolean(store.is_verified||store.verification_badge);
 return <main className="mx-auto max-w-6xl px-4 py-7 sm:px-6 lg:px-8"><Link href="/marketplace" className="inline-flex items-center gap-2 text-sm font-medium text-[var(--muted)]"><ArrowLeft size={16}/> Marketplace</Link>
  <section className="mt-5 overflow-hidden rounded-[2rem] border border-[var(--border)] bg-[var(--surface)] shadow-[var(--shadow-md)]"><div className="h-28 bg-[var(--background)] sm:h-40"/><div className="px-6 pb-7 sm:px-9"><div className="-mt-10 flex flex-col gap-5 sm:-mt-12 sm:flex-row sm:items-end sm:justify-between"><div className="flex items-end gap-4"><div className="flex h-20 w-20 shrink-0 items-center justify-center overflow-hidden rounded-3xl border-4 border-[var(--surface)] bg-[var(--background)] shadow-[var(--shadow-sm)] sm:h-24 sm:w-24">{store.logo_url?<img src={store.logo_url} alt={`${store.name} logo`} className="h-full w-full object-cover"/>:<Store size={32} className="text-[var(--muted)]"/>}</div><div className="min-w-0 pb-1"><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">{store.name}</h1>{verified&&<span className="inline-flex items-center gap-1 rounded-full border border-[var(--border)] px-2.5 py-1 text-[11px] font-semibold"><CheckCircle2 size={12}/> Verified</span>}</div>{store.public_id&&<p className="mt-1 font-mono text-[10px] text-[var(--muted)]">Store ID: {store.public_id}</p>}</div></div><div className="flex flex-wrap gap-2"><button className="inline-flex items-center gap-2 rounded-xl border border-[var(--border)] px-3.5 py-2.5 text-sm font-semibold"><ExternalLink size={15}/> Share store</button>{store.owner_user_id&&<Link href={`/profile/${store.owner_user_id}`} className="inline-flex items-center gap-2 rounded-xl bg-[var(--primary)] px-3.5 py-2.5 text-sm font-semibold text-[var(--background)]"><UserRound size={15}/> Seller profile</Link>}</div></div><p className="mt-5 max-w-3xl text-sm leading-7 text-[var(--muted)]">{store.description||"Discover products and offers from this DRIGHT seller."}</p><div className="mt-5 flex flex-wrap gap-3 text-xs text-[var(--muted)]"><span className="inline-flex items-center gap-1.5 rounded-full bg-[var(--background)] px-3 py-2"><Package size={14}/> {items.length} published {items.length===1?"listing":"listings"}</span>{verified&&<span className="inline-flex items-center gap-1.5 rounded-full bg-[var(--background)] px-3 py-2"><CheckCircle2 size={14}/> Verified store</span>}</div></div></section>
  <section className="mt-7"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-widest text-[var(--muted)]">Store catalog</p><h2 className="mt-1 text-2xl font-semibold">Available listings</h2></div>{store.owner_user_id&&<Link href={`/messages/new?user=${encodeURIComponent(store.owner_user_id)}`} className="inline-flex items-center gap-2 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 py-2.5 text-sm font-semibold"><MessageCircle size={15}/> Contact seller</Link>}</div>{items.length===0?<div className="mt-5 rounded-[2rem] border border-dashed border-[var(--border)] bg-[var(--surface)] p-12 text-center"><Package className="mx-auto" size={30}/><h3 className="mt-4 font-semibold">No published listings</h3><p className="mt-2 text-sm text-[var(--muted)]">This store does not currently have public listings.</p></div>:<div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map(item=><Link key={item.id} href={`/marketplace/${item.id}`} className="group rounded-[1.5rem] border border-[var(--border)] bg-[var(--surface)] p-5 shadow-[var(--shadow-sm)] transition hover:-translate-y-0.5 hover:shadow-[var(--shadow-md)]"><div className="flex h-36 items-center justify-center rounded-2xl bg-[var(--background)]"><Package size={30} className="text-[var(--muted)]"/></div><div className="mt-4 flex items-start justify-between gap-3"><h3 className="font-semibold leading-6 group-hover:underline">{item.title}</h3>{item.item_type&&<span className="shrink-0 rounded-full border border-[var(--border)] px-2 py-1 text-[10px] font-semibold text-[var(--muted)]">{item.item_type}</span>}</div>{item.description&&<p className="mt-2 line-clamp-2 text-sm leading-5 text-[var(--muted)]">{item.description}</p>}<p className="mt-4 text-lg font-semibold">{item.price==null?"Contact seller":`${item.currency_code||"USD"} ${item.price.toLocaleString()}`}</p><p className="mt-1 font-mono text-[10px] text-[var(--muted)]">ID: {item.id}</p></Link>)}</div>}</section>
 </main>;
}
function useParamsId(){const [id,setId]=useState("");useEffect(()=>{setId(window.location.pathname.split("/").filter(Boolean).pop()||"")},[]);return {id}}
