"use client";

import { useEffect, useState } from "react";
import { Loader2, Plus, Save, ShieldCheck } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Role = { id:string; name:string; slug:string; description:string|null; is_system_role:boolean; is_active:boolean };
type Permission = { id:string; name:string; slug:string; resource:string|null; action:string|null };

export default function RolesPage() {
  const supabase=createClient();
  const [roles,setRoles]=useState<Role[]>([]); const [permissions,setPermissions]=useState<Permission[]>([]); const [selected,setSelected]=useState(""); const [grants,setGrants]=useState<Set<string>>(new Set());
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [creating,setCreating]=useState(false); const [error,setError]=useState("");
  const [newRole,setNewRole]=useState({name:"",slug:"",description:""}); const [newGrants,setNewGrants]=useState<Set<string>>(new Set());

  async function load(){
    setLoading(true); const {data:{user}}=await supabase.auth.getUser(); if(!user){window.location.href="/login?next=/admin/roles";return;}
    const {data:allowed}=await supabase.rpc("admin_has_permission",{p_permission:"roles.manage",p_user_id:user.id}); if(!allowed){setError("You do not have permission to manage roles.");setLoading(false);return;}
    const [{data:r,error:re},{data:p,error:pe}]=await Promise.all([
      supabase.from("roles").select("id,name,slug,description,is_system_role,is_active").order("name"),
      supabase.from("permissions").select("id,name,slug,resource,action").order("slug")
    ]);
    if(re||pe)setError(re?.message||pe?.message||""); setRoles((r||[]) as Role[]); setPermissions((p||[]) as Permission[]); if(!selected&&r?.length)setSelected(r[0].id); setLoading(false);
  }
  async function loadGrants(roleId:string){const {data,error:e}=await supabase.from("role_permissions").select("permission_id").eq("role_id",roleId);if(e)setError(e.message);setGrants(new Set((data||[]).map(x=>x.permission_id)));}
  useEffect(()=>{load();},[]); useEffect(()=>{if(selected)loadGrants(selected);},[selected]);
  async function save(){setSaving(true);setError("");const {error:e}=await supabase.rpc("admin_set_role_permissions",{p_role_id:selected,p_permission_ids:[...grants]});if(e)setError(e.message);else await load();setSaving(false);}
  async function createRole(){setCreating(true);setError("");const slug=newRole.slug.trim().toLowerCase().replace(/[^a-z0-9_]+/g,"_");const {data,error:e}=await supabase.rpc("admin_create_role",{p_name:newRole.name.trim(),p_slug:slug,p_description:newRole.description.trim()||null,p_permission_ids:[...newGrants]});if(e)setError(e.message);else {setNewRole({name:"",slug:"",description:""});setNewGrants(new Set());await load();if(data?.id)setSelected(data.id);}setCreating(false);}
  if(error&&!roles.length&&!loading)return <main className="mx-auto max-w-xl px-4 py-16 text-center"><ShieldCheck className="mx-auto" size={40}/><h1 className="mt-4 text-2xl font-semibold">Access restricted</h1><p className="mt-2 text-sm text-[var(--muted)]">{error}</p></main>;
  const selectedRole=roles.find(r=>r.id===selected);
  return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div><p className="text-xs font-semibold uppercase tracking-widest text-[var(--muted)]">Governance · RBAC</p><h1 className="mt-1 text-3xl font-semibold">Roles & Permissions</h1><p className="mt-2 text-sm text-[var(--muted)]">Manage custom administrator roles and granular permission bundles through the existing DRIGHT authorization model.</p></div>{error&&<p className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <section className="mt-6 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><div className="flex items-center gap-2"><Plus size={18}/><h2 className="font-semibold">Create custom administrator role</h2></div><div className="mt-4 grid gap-3 md:grid-cols-3"><input value={newRole.name} onChange={e=>setNewRole({...newRole,name:e.target.value})} placeholder="Role name e.g. Risk Operations Admin" className="rounded-xl border border-[var(--border)] bg-[var(--background)] px-3 py-2.5 text-sm"/><input value={newRole.slug} onChange={e=>setNewRole({...newRole,slug:e.target.value})} placeholder="role_slug" className="rounded-xl border border-[var(--border)] bg-[var(--background)] px-3 py-2.5 text-sm"/><input value={newRole.description} onChange={e=>setNewRole({...newRole,description:e.target.value})} placeholder="Description" className="rounded-xl border border-[var(--border)] bg-[var(--background)] px-3 py-2.5 text-sm"/></div><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{permissions.map(p=><label key={p.id} className="flex items-start gap-2 rounded-xl border border-[var(--border)] p-2.5 text-xs"><input type="checkbox" checked={newGrants.has(p.id)} onChange={()=>setNewGrants(s=>{const n=new Set(s);n.has(p.id)?n.delete(p.id):n.add(p.id);return n})} className="mt-0.5"/><span>{p.slug}</span></label>)}</div><button onClick={createRole} disabled={creating||!newRole.name.trim()||!newRole.slug.trim()} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-[var(--primary)] px-4 py-2.5 text-sm font-semibold text-[var(--background)]">{creating?<Loader2 className="animate-spin" size={16}/>:<Plus size={16}/>}Create role</button></section>
    <div className="mt-5 grid gap-5 lg:grid-cols-[280px_1fr]"><section className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-3"><p className="px-3 py-2 text-xs font-semibold uppercase tracking-widest text-[var(--muted)]">Roles</p>{loading?<div className="p-4 text-sm text-[var(--muted)]">Loading…</div>:roles.map(r=><button key={r.id} onClick={()=>setSelected(r.id)} className={`w-full rounded-xl px-3 py-3 text-left ${selected===r.id?"bg-[var(--primary)] text-[var(--background)]":"hover:bg-[var(--background)]"}`}><p className="text-sm font-semibold">{r.name}</p><p className="mt-1 text-[11px] opacity-70">{r.slug}{r.is_system_role?" · system":" · custom"}</p></button>)}</section><section className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="font-semibold">{selectedRole?.name||"Select a role"}</h2><p className="text-xs text-[var(--muted)]">{selectedRole?.description}</p></div><button onClick={save} disabled={saving||!selected} className="inline-flex items-center gap-2 rounded-xl bg-[var(--primary)] px-4 py-2.5 text-sm font-semibold text-[var(--background)]">{saving?<Loader2 className="animate-spin" size={16}/>:<Save size={16}/>}Save</button></div><div className="mt-5 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{permissions.map(p=><label key={p.id} className="flex cursor-pointer items-start gap-3 rounded-xl border border-[var(--border)] p-3"><input type="checkbox" checked={grants.has(p.id)} onChange={()=>setGrants(s=>{const n=new Set(s);n.has(p.id)?n.delete(p.id):n.add(p.id);return n})} className="mt-1"/><span><span className="block text-sm font-medium">{p.slug}</span><span className="mt-1 block text-xs text-[var(--muted)]">{p.name}</span></span></label>)}</div></section></div></main>;
}
