"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Compass, Plus, Users, X, Search } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Community={id:string;public_id:string;name:string;slug:string;description:string|null;access_type:string;join_policy:string;category:string|null;tags:string[];member_count:number;post_count:number;created_at:string};

export default function CommunitiesPage(){
 const supabase=useMemo(()=>createClient(),[]); const [items,setItems]=useState<Community[]>([]); const [joined,setJoined]=useState<Set<string>>(new Set()); const [query,setQuery]=useState(""); const [category,setCategory]=useState(""); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null); const [createOpen,setCreateOpen]=useState(false); const [form,setForm]=useState({name:"",slug:"",description:"",category:"",visibility:"public",join_policy:"open"}); const [message,setMessage]=useState("");
 const load=async()=>{setLoading(true); const [{data},{data:{user}}]=await Promise.all([supabase.rpc("search_communities",{p_query:query||null,p_category:category||null,p_limit:48,p_offset:0}),supabase.auth.getUser()]); if(user){const {data:m}=await supabase.from("community_members").select("community_id").eq("user_id",user.id).eq("status","active");setJoined(new Set((m||[]).map((x:{community_id:string})=>x.community_id)));} setItems((data||[]) as Community[]);setLoading(false);};
 useEffect(()=>{void load();},[query,category]);
 async function toggleJoin(c:Community){const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href=`/login?next=/communities`;return;}setBusy(c.id);const action=joined.has(c.id)?supabase.rpc("leave_community",{p_community_id:c.id}):supabase.rpc("request_community_join",{p_community_id:c.id});const {data,error}=await action;if(!error){setJoined(prev=>{const n=new Set(prev);if(joined.has(c.id))n.delete(c.id);else if(data!=="invite_required")n.add(c.id);return n;});if(data==="pending")setMessage("Join request sent for approval.");if(data==="invite_required")setMessage("This community is invite-only.");}setBusy(null);}
 async function createCommunity(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;setMessage("");const slug=form.slug.trim().toLowerCase().replace(/[^a-z0-9-]+/g,"-").replace(/^-|-$/g,"");if(!form.name.trim()||!slug){setMessage("Community name and a valid slug are required.");return;}const {error}=await supabase.from("communities").insert({owner_user_id:user.id,name:form.name.trim(),slug,description:form.description.trim()||null,visibility:form.visibility,status:"draft",category:form.category.trim()||null,join_policy:form.join_policy});if(error){setMessage(error.message);return;}setCreateOpen(false);setForm({name:"",slug:"",description:"",category:"",visibility:"public",join_policy:"open"});setMessage("Community created as a draft and remains subject to DRIGHT review/publication controls.");}
 return <main className="mx-auto max-w-7xl px-4 py-7 sm:px-6 lg:px-8"><section className="rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-6 sm:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--muted)]">DRIGHT Social</p><h1 className="mt-2 text-3xl font-bold">Communities</h1><p className="mt-2 max-w-2xl text-sm text-[var(--muted)]">Discover communities around products, services, courses, jobs, creators and shared interests.</p></div><button type="button" onClick={()=>setCreateOpen(true)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[var(--primary)] px-4 py-2.5 text-sm font-semibold text-[var(--primary-contrast)]"><Plus size={16}/> Create community</button></div><div className="mt-5 grid gap-3 md:grid-cols-[1fr_220px]"><label className="relative"><Search size={16} className="absolute left-3 top-3.5 text-[var(--muted)]"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by name, ID, description or tag…" className="w-full rounded-xl border border-[var(--border)] bg-[var(--background)] py-3 pl-9 pr-4 text-sm outline-none focus:ring-2 focus:ring-[var(--accent)]"/></label><input value={category} onChange={e=>setCategory(e.target.value)} placeholder="Category" className="rounded-xl border border-[var(--border)] bg-[var(--background)] px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-[var(--accent)]"/></div>{message&&<p role="status" className="mt-3 rounded-xl border border-[var(--border)] bg-[var(--background)] px-4 py-3 text-sm text-[var(--muted)]">{message}</p>}</section>
 <section className="mt-7">{loading?<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{Array.from({length:6}).map((_,i)=><div key={i} className="h-52 animate-pulse rounded-2xl bg-[var(--surface)]"/>)}</div>:items.length===0?<div className="rounded-2xl border border-dashed border-[var(--border)] p-12 text-center"><Compass className="mx-auto text-[var(--muted)]"/><h2 className="mt-4 font-semibold">No public communities found</h2><p className="mt-2 text-sm text-[var(--muted)]">Try a different search or create a new community.</p></div>:<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map(c=><article key={c.id} className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold"><Link href={`/communities/${c.slug}`} className="hover:underline">{c.name}</Link></h2><p className="mt-1 text-xs text-[var(--muted)]">{c.public_id}</p></div><span className="rounded-full border border-[var(--border)] px-2.5 py-1 text-[10px] font-semibold capitalize">{c.join_policy.replaceAll("_"," ")}</span></div><p className="mt-4 min-h-10 text-sm leading-5 text-[var(--muted)]">{c.description||"A DRIGHT community."}</p><div className="mt-4 flex flex-wrap gap-2">{(c.tags||[]).slice(0,3).map(t=><span key={t} className="rounded-full bg-[var(--background)] px-2 py-1 text-[10px] text-[var(--muted)]">#{t}</span>)}</div><div className="mt-5 flex items-center justify-between gap-3"><span className="inline-flex items-center gap-3 text-xs text-[var(--muted)]"><span className="inline-flex items-center gap-1"><Users size={14}/>{c.member_count}</span><span>{c.post_count} posts</span></span><button onClick={()=>void toggleJoin(c)} disabled={busy===c.id} className="rounded-xl bg-[var(--primary)] px-4 py-2 text-xs font-semibold text-[var(--primary-contrast)]">{joined.has(c.id)?"Leave":"Join"}</button></div></article>)}</div>}</section>
 {createOpen&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-lg rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-6 shadow-2xl"><div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">Create a community</h2><p className="mt-1 text-sm text-[var(--muted)]">New communities start as drafts and follow DRIGHT publication/moderation controls.</p></div><button onClick={()=>setCreateOpen(false)} aria-label="Close"><X/></button></div><div className="mt-6 space-y-3"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Community name" className="w-full rounded-xl border border-[var(--border)] bg-[var(--background)] px-4 py-3 text-sm"/><input value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})} placeholder="slug" className="w-full rounded-xl border border-[var(--border)] bg-[var(--background)] px-4 py-3 text-sm"/><input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="Category" className="w-full rounded-xl border border-[var(--border)] bg-[var(--background)] px-4 py-3 text-sm"/><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Description" rows={4} className="w-full rounded-xl border border-[var(--border)] bg-[var(--background)] px-4 py-3 text-sm"/><div className="grid gap-3 sm:grid-cols-2"><select value={form.visibility} onChange={e=>setForm({...form,visibility:e.target.value})} className="rounded-xl border border-[var(--border)] bg-[var(--background)] px-4 py-3 text-sm"><option value="public">Public</option><option value="private">Private</option></select><select value={form.join_policy} onChange={e=>setForm({...form,join_policy:e.target.value})} className="rounded-xl border border-[var(--border)] bg-[var(--background)] px-4 py-3 text-sm"><option value="open">Open join</option><option value="approval">Approval required</option><option value="invite_only">Invite only</option></select></div>{message&&<p className="text-sm text-[var(--muted)]">{message}</p>}<button onClick={()=>void createCommunity()} className="w-full rounded-xl bg-[var(--primary)] px-4 py-3 text-sm font-semibold text-[var(--primary-contrast)]">Create draft</button></div></div></div>}
 </main>;
}
