"use client";
import { useEffect,useMemo,useState } from "react";
import { createClient } from "@/lib/supabase/client";
export default function Referrals(){
 const s=createClient(); const [rows,setRows]=useState<any[]>([]); const [links,setLinks]=useState<any[]>([]); const [summary,setSummary]=useState<any>({}); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 useEffect(()=>{(async()=>{const {data:{user}}=await s.auth.getUser();if(!user){location.href="/login?next=/referrals";return}const [r,l,sm]=await Promise.all([s.from("referral_rewards").select("reward_id,referral_id,beneficiary_user_id,level,reward_percent,basis_amount,reward_amount,currency_code,qualifying_order_id,status,available_at,expires_at,paid_at,created_at").eq("beneficiary_user_id",user.id).order("created_at",{ascending:false}),s.from("referrals").select("referral_id,referred_user_id,parent_referral_id,level,status,qualifying_event,qualifying_order_id,expires_at,qualified_at,created_at").eq("referrer_user_id",user.id).order("created_at",{ascending:false}),s.rpc("get_referral_summary",{p_user_id:user.id})]);if(r.error)setError(r.error.message);setRows(r.data||[]);setLinks(l.data||[]);setSummary(sm.data||{});setLoading(false)})()},[]);
 const total=useMemo(()=>rows.reduce((n,r)=>n+Number(r.reward_amount||0),0),[rows]);
 return <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8"><h1 className="text-3xl font-semibold">Referral Center</h1><p className="mt-2 text-sm text-[var(--muted)]">Three-level referral rewards are tied to qualifying events and remain auditable through their lifecycle.</p>{error&&<p className="mt-3 text-sm text-red-500">{error}</p>}<section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Direct",summary.direct||0],["Level 2",summary.level2||0],["Level 3",summary.level3||0],["Available",Number(summary.available||0).toFixed(2)],["Total rewards",total.toFixed(2)]].map(([l,v])=><article key={String(l)} className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-4"><p className="text-xs uppercase tracking-wide text-[var(--muted)]">{l}</p><p className="mt-2 text-2xl font-semibold">{v}</p></article>)}</section><section className="mt-6 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><h2 className="font-semibold">My referral relationships</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr className="border-b border-[var(--border)]"><th className="p-3">Referral ID</th><th>Level</th><th>Status</th><th>Event</th><th>Expires</th></tr></thead><tbody>{links.map(r=><tr key={r.referral_id} className="border-b border-[var(--border)]"><td className="p-3 font-medium">{r.referral_id}</td><td>{r.level}</td><td>{r.status}</td><td>{r.qualifying_event||"—"}</td><td>{r.expires_at?new Date(r.expires_at).toLocaleDateString():"—"}</td></tr>)}</tbody></table>{!loading&&!links.length&&<p className="py-6 text-sm text-[var(--muted)]">No direct referral relationships yet.</p>}</div></section><section className="mt-6 overflow-x-auto rounded-2xl border border-[var(--border)] bg-[var(--surface)]"><table className="w-full min-w-[850px] text-left text-sm"><thead><tr className="border-b border-[var(--border)]"><th className="p-4">Reward ID</th><th>Level</th><th>Basis</th><th>Reward</th><th>Status</th><th>Expires</th><th className="p-4">Date</th></tr></thead><tbody>{loading?<tr><td className="p-6" colSpan={7}>Loading…</td></tr>:rows.map(r=><tr className="border-b border-[var(--border)]" key={r.reward_id}><td className="p-4 font-medium">{r.reward_id}</td><td>{r.level}</td><td>{r.basis_amount} {r.currency_code}</td><td>{r.reward_amount} {r.currency_code}</td><td>{r.status}</td><td>{r.expires_at?new Date(r.expires_at).toLocaleDateString():"—"}</td><td className="p-4">{r.created_at?new Date(r.created_at).toLocaleString():"—"}</td></tr>)}</tbody></table>{!loading&&!rows.length&&<p className="p-8 text-sm text-[var(--muted)]">No referral rewards yet.</p>}</section></main>;
}
