"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, CircleDollarSign, CreditCard, Search, ShieldCheck, WalletCards } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Tx={id:string;transaction_id:string;amount:number;currency_code:string;provider:string;provider_transaction_id:string|null;status:string;created_at:string};
type Payout={id:string;payout_id:string;user_id:string;amount:number;currency_code:string;status:string;created_at:string};
type Commission={id:string;affiliate_user_id:string;amount:number;currency_code:string;status:string;created_at:string};

export default function FinanceAdminPage(){
 const s=createClient(); const [allowed,setAllowed]=useState(false); const [error,setError]=useState(""); const [loading,setLoading]=useState(true); const [q,setQ]=useState(""); const [tab,setTab]=useState("transactions"); const [tx,setTx]=useState<Tx[]>([]); const [payouts,setPayouts]=useState<Payout[]>([]); const [commissions,setCommissions]=useState<Commission[]>([]); const [walletCount,setWalletCount]=useState(0); const [refundCount,setRefundCount]=useState(0);
 useEffect(()=>{(async()=>{const {data:{user}}=await s.auth.getUser();if(!user){location.href="/login?next=/admin/finance";return}const {data:isAdmin,error:ae}=await s.rpc("is_super_admin",{check_user_id:user.id});if(ae||!isAdmin){setError("You do not have permission to access Finance.");setLoading(false);return}setAllowed(true);const [a,b,c,d,e]=await Promise.all([s.from("transactions").select("id,transaction_id,amount,currency_code,provider,provider_transaction_id,status,created_at").order("created_at",{ascending:false}).limit(200),s.from("payouts").select("id,payout_id,user_id,amount,currency_code,status,created_at").order("created_at",{ascending:false}).limit(200),s.from("commissions").select("id,affiliate_user_id,amount,currency_code,status,created_at").order("created_at",{ascending:false}).limit(200),s.from("wallets").select("id",{count:"exact",head:true}),s.from("refund_disputes").select("id",{count:"exact",head:true})]);if(a.error)setError(a.error.message);setTx((a.data||[]) as Tx[]);setPayouts((b.data||[]) as Payout[]);setCommissions((c.data||[]) as Commission[]);setWalletCount(d.count||0);setRefundCount(e.count||0);setLoading(false)})()},[]);
 const filter=(r:any)=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase());
 const volume=useMemo(()=>tx.reduce((n,r)=>n+(Number(r.amount)||0),0),[tx]);
 if(error&&!allowed&&!loading)return <div className="mx-auto max-w-xl px-4 py-16 text-center"><ShieldCheck size={40} className="mx-auto"/><h1 className="mt-5 text-2xl font-semibold">Access restricted</h1><p className="mt-3 text-sm text-[var(--muted)]">{error}</p><Link href="/dashboard" className="mt-6 inline-flex items-center gap-2 rounded-xl border border-[var(--border)] px-4 py-2.5 text-sm font-semibold"><ArrowLeft size={16}/> Dashboard</Link></div>;
 return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-widest text-[var(--muted)]">Admin · Finance</p><h1 className="mt-1 text-3xl font-semibold">Finance Control Center</h1><p className="mt-2 text-sm text-[var(--muted)]">Monitor transactions, commissions, wallets, payouts and refund exposure. Financial mutations remain server-authorized.</p></div><Link href="/dashboard" className="inline-flex items-center gap-2 text-sm text-[var(--muted)]"><ArrowLeft size={16}/> Dashboard</Link></div>
 <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><article className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><CreditCard size={19}/><p className="mt-4 text-sm text-[var(--muted)]">Transaction volume</p><p className="mt-1 text-2xl font-semibold">{volume.toLocaleString(undefined,{maximumFractionDigits:2})}</p></article><article className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><WalletCards size={19}/><p className="mt-4 text-sm text-[var(--muted)]">Wallets</p><p className="mt-1 text-2xl font-semibold">{walletCount}</p></article><article className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><CircleDollarSign size={19}/><p className="mt-4 text-sm text-[var(--muted)]">Payout requests</p><p className="mt-1 text-2xl font-semibold">{payouts.length}</p></article><article className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><ShieldCheck size={19}/><p className="mt-4 text-sm text-[var(--muted)]">Refund/dispute cases</p><p className="mt-1 text-2xl font-semibold">{refundCount}</p></article></div>
 <div className="mt-6 flex flex-wrap gap-2">{[["transactions","Transactions"],["commissions","Commissions"],["payouts","Payouts"]].map(([v,l])=><button key={v} onClick={()=>setTab(v)} className={`rounded-xl border px-4 py-2.5 text-sm font-semibold ${tab===v?"bg-[var(--primary)] text-[var(--background)]":"border-[var(--border)] bg-[var(--surface)]"}`}>{l}</button>)}<Link href="/admin/refunds" className="rounded-xl border border-[var(--border)] bg-[var(--surface)] px-4 py-2.5 text-sm font-semibold">Refunds & disputes</Link></div>
 <label className="mt-4 flex items-center gap-2 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search IDs, users, providers or status…" className="w-full bg-transparent py-3 text-sm outline-none"/></label>
 <section className="mt-5 overflow-x-auto rounded-2xl border border-[var(--border)] bg-[var(--surface)]">{loading?<div className="p-8 text-sm text-[var(--muted)]">Loading finance data…</div>:tab==="transactions"?<table className="w-full text-left text-sm"><thead><tr className="border-b border-[var(--border)]"><th className="p-4">Transaction</th><th>Provider</th><th>Amount</th><th>Status</th><th className="p-4">Date</th></tr></thead><tbody>{tx.filter(filter).map(r=><tr key={r.id} className="border-b border-[var(--border)]"><td className="p-4 font-semibold">{r.transaction_id}</td><td>{r.provider}</td><td>{r.amount} {r.currency_code}</td><td>{r.status}</td><td className="p-4">{new Date(r.created_at).toLocaleString()}</td></tr>)}</tbody></table>:tab==="commissions"?<table className="w-full text-left text-sm"><thead><tr className="border-b border-[var(--border)]"><th className="p-4">Commission</th><th>Affiliate</th><th>Amount</th><th>Status</th><th className="p-4">Date</th></tr></thead><tbody>{commissions.filter(filter).map(r=><tr key={r.id} className="border-b border-[var(--border)]"><td className="p-4">{r.id}</td><td>{r.affiliate_user_id}</td><td>{r.amount} {r.currency_code}</td><td>{r.status}</td><td className="p-4">{new Date(r.created_at).toLocaleString()}</td></tr>)}</tbody></table>:<table className="w-full text-left text-sm"><thead><tr className="border-b border-[var(--border)]"><th className="p-4">Payout</th><th>User</th><th>Amount</th><th>Status</th><th className="p-4">Date</th></tr></thead><tbody>{payouts.filter(filter).map(r=><tr key={r.id} className="border-b border-[var(--border)]"><td className="p-4 font-semibold">{r.payout_id||r.id}</td><td>{r.user_id}</td><td>{r.amount} {r.currency_code}</td><td>{r.status}</td><td className="p-4">{new Date(r.created_at).toLocaleString()}</td></tr>)}</tbody></table>}</section></main>;
}
