"use client";

import { useEffect, useMemo, useState } from "react";
import { Gavel, Loader2, ShieldAlert } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Report={id:string;report_id:string;reporter_user_id:string|null;target_type:string;target_id:string;reason_type:string;reason:string;status:string;severity:string;priority:number;category:string|null;assigned_admin_id:string|null;created_at:string;updated_at:string};

export default function ModerationPage(){
 const supabase=createClient();const [reports,setReports]=useState<Report[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [busy,setBusy]=useState<string|null>(null);const [statusFilter,setStatusFilter]=useState("all");const [severityFilter,setSeverityFilter]=useState("all");
 async function load(){setLoading(true);const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href="/login?next=/admin/moderation";return;}const {data:ok}=await supabase.rpc("admin_has_permission",{p_permission:"moderation.manage",p_user_id:user.id});if(!ok){setError("You do not have permission to manage moderation.");setLoading(false);return;}const {data,error:queryError}=await supabase.from("reports").select("id,report_id,reporter_user_id,target_type,target_id,reason_type,reason,status,severity,priority,category,assigned_admin_id,created_at,updated_at").order("priority",{ascending:true}).order("created_at",{ascending:false}).limit(200);if(queryError)setError(queryError.message);setReports((data||[]) as Report[]);setLoading(false);}
 useEffect(()=>{load();},[]);
 async function action(id:string,actionName:string){setBusy(id);const {error:e}=await supabase.rpc("moderation_record_action",{p_report_id:id,p_action:actionName,p_reason:`Moderation action: ${actionName}`});if(e)setError(e.message);else await load();setBusy(null);}
 const filtered=useMemo(()=>reports.filter(r=>(statusFilter==="all"||r.status===statusFilter)&&(severityFilter==="all"||r.severity===severityFilter)),[reports,statusFilter,severityFilter]);
 if(error&&!reports.length&&!loading)return <main className="mx-auto max-w-xl px-4 py-16 text-center"><ShieldAlert className="mx-auto" size={40}/><h1 className="mt-4 text-2xl font-semibold">Access restricted</h1><p className="mt-2 text-sm text-[var(--muted)]">{error}</p></main>;
 return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><p className="text-xs font-semibold uppercase tracking-widest text-[var(--muted)]">Trust & Safety</p><h1 className="mt-1 text-3xl font-semibold">Moderation Center</h1><p className="mt-2 text-sm text-[var(--muted)]">Centralized reports, review decisions, escalation and auditable moderation actions.</p>{error&&<p className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}
 <div className="mt-6 flex flex-wrap gap-2"><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} className="rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 py-2 text-sm"><option value="all">All statuses</option><option value="submitted">Submitted</option><option value="under_review">Under review</option><option value="actioned">Actioned</option><option value="escalated">Escalated</option><option value="resolved">Resolved</option><option value="dismissed">Dismissed</option><option value="closed">Closed</option></select><select value={severityFilter} onChange={e=>setSeverityFilter(e.target.value)} className="rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 py-2 text-sm"><option value="all">All severities</option><option value="critical">Critical</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select><span className="self-center text-xs text-[var(--muted)]">{filtered.length} case{filtered.length===1?"":"s"}</span></div>
 <section className="mt-4 overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--surface)]">{loading?<div className="p-8 text-sm text-[var(--muted)]">Loading moderation queue…</div>:filtered.length===0?<div className="p-8 text-sm text-[var(--muted)]">No reports match the current filters.</div>:<div className="divide-y divide-[var(--border)]">{filtered.map(r=><div key={r.id} className="p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-xs text-[var(--muted)]">{r.report_id}</span><span className="rounded-full border border-[var(--border)] px-2 py-1 text-[10px] uppercase">{r.status}</span><span className="rounded-full border border-[var(--border)] px-2 py-1 text-[10px] uppercase">{r.severity}</span><span className="rounded-full border border-[var(--border)] px-2 py-1 text-[10px] uppercase">priority {r.priority}</span>{r.category&&<span className="rounded-full border border-[var(--border)] px-2 py-1 text-[10px]">{r.category}</span>}</div><p className="mt-2 text-sm font-semibold">{r.target_type}: {r.target_id}</p><p className="mt-1 text-sm text-[var(--muted)]">{r.reason}</p><p className="mt-2 text-[11px] text-[var(--muted)]">Reported {new Date(r.created_at).toLocaleString()}{r.assigned_admin_id?` · Assigned ${r.assigned_admin_id}`:" · Unassigned"}</p></div><div className="flex flex-wrap gap-2"><button disabled={busy===r.id} onClick={()=>action(r.id,"resolve")} className="rounded-xl bg-[var(--primary)] px-3 py-2 text-xs font-semibold text-[var(--background)]">Resolve</button><button disabled={busy===r.id} onClick={()=>action(r.id,"dismiss")} className="rounded-xl border border-[var(--border)] px-3 py-2 text-xs font-semibold">Dismiss</button><button disabled={busy===r.id} onClick={()=>action(r.id,"request_changes")} className="rounded-xl border border-[var(--border)] px-3 py-2 text-xs font-semibold">Request changes</button><button disabled={busy===r.id} onClick={()=>action(r.id,"suspend")} className="rounded-xl border border-[var(--border)] px-3 py-2 text-xs font-semibold">Suspend</button><button disabled={busy===r.id} onClick={()=>action(r.id,"escalate")} className="inline-flex items-center gap-1 rounded-xl border border-[var(--border)] px-3 py-2 text-xs font-semibold"><Gavel size={13}/>Escalate</button>{busy===r.id&&<Loader2 className="animate-spin self-center" size={16}/>}</div></div></div>)}</div>}</section></main>;
}
