"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { AlertTriangle, BarChart3, Headphones, RefreshCw, Search, Users, UserPlus } from "lucide-react";

const supabase = createClient();

type Customer = { user_id:string; username:string|null; full_name:string|null; account_status:string; customer_id:string|null; lifecycle_stage:string|null; health_state:string|null; health_score:number|null; churn_risk:number|null; recovery_status:string|null; last_activity_at:string|null; order_count:number; open_ticket_count:number; lifetime_order_value:number };
type Ticket = { id:string; ticket_id:string; customer_user_id:string; subject:string; category:string; priority:string; status:string; created_at:string; assigned_agent_id:string|null };
type Lead = { id:string; lead_id:string; organization_name:string|null; contact_name:string|null; stage:string; status:string; value_estimate:number|null; currency_code:string|null; next_action:string|null };

export default function CrmAdminPage(){
 const [customers,setCustomers]=useState<Customer[]>([]); const [tickets,setTickets]=useState<Ticket[]>([]); const [leads,setLeads]=useState<Lead[]>([]);
 const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [query,setQuery]=useState(""); const [tab,setTab]=useState<"customers"|"support"|"sales">("customers");
 async function load(){
  setLoading(true); setError("");
  const {data:{user}}=await supabase.auth.getUser();
  if(!user){location.href="/login?next=/admin/crm";return;}
  const {data:allowed}=await supabase.rpc("admin_has_permission",{p_permission:"crm.customers.view",p_user_id:user.id});
  if(!allowed){location.href="/dashboard";return;}
  const [c,t,l]=await Promise.all([
   supabase.rpc("crm_get_customer_summary"),
   supabase.from("crm_support_tickets").select("id,ticket_id,customer_user_id,subject,category,priority,status,created_at,assigned_agent_id").order("created_at",{ascending:false}).limit(100),
   supabase.from("crm_sales_leads").select("id,lead_id,organization_name,contact_name,stage,status,value_estimate,currency_code,next_action").order("created_at",{ascending:false}).limit(100)
  ]);
  if(c.error) setError(c.error.message); else setCustomers((c.data||[]) as Customer[]);
  if(t.error && !error) setError(t.error.message); else setTickets((t.data||[]) as Ticket[]);
  if(l.error && !error) setError(l.error.message); else setLeads((l.data||[]) as Lead[]);
  setLoading(false);
 }
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>customers.filter(c=>[c.customer_id,c.username,c.full_name,c.user_id,c.lifecycle_stage,c.health_state].some(v=>String(v||"").toLowerCase().includes(query.toLowerCase()))),[customers,query]);
 const stats={customers:customers.length,atRisk:customers.filter(c=>c.health_state==="At Risk"||c.health_state==="Critical").length,openTickets:tickets.filter(t=>!['resolved','closed'].includes(t.status)).length,openLeads:leads.filter(l=>l.status==='open').length};
 if(loading)return <main className="p-6"><p className="text-sm text-[var(--muted)]">Loading CRM intelligence…</p></main>;
 return <main className="mx-auto max-w-[1500px] p-4 sm:p-6 lg:p-8">
  <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-widest text-[var(--muted)]">Enterprise CRM</p><h1 className="mt-1 text-3xl font-semibold">Customer Success & Operations</h1><p className="mt-2 max-w-3xl text-sm text-[var(--muted)]">Unified customer intelligence connected to DRIGHT users, orders, payments, subscriptions, support, campaigns and sales systems.</p></div><button onClick={load} className="inline-flex items-center justify-center gap-2 rounded-xl border border-[var(--border)] px-4 py-2 text-sm"><RefreshCw size={16}/> Refresh</button></div>
  {error&&<div className="mt-4 rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-500">{error}</div>}
  <section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[Users,"Customers",stats.customers],[AlertTriangle,"At-risk",stats.atRisk],[Headphones,"Open support",stats.openTickets],[UserPlus,"Open leads",stats.openLeads]].map(([Icon,label,value])=><article key={String(label)} className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><div className="flex items-center justify-between"><span className="text-xs uppercase tracking-wider text-[var(--muted)]">{label}</span><Icon size={18}/></div><p className="mt-3 text-3xl font-semibold">{value}</p></article>)}</section>
  <div className="mt-6 flex flex-wrap gap-2 border-b border-[var(--border)] pb-3">{[["customers","Customers",Users],["support","Support",Headphones],["sales","Sales",BarChart3]].map(([key,label,Icon])=><button key={String(key)} onClick={()=>setTab(key as typeof tab)} className={`inline-flex items-center gap-2 rounded-xl px-4 py-2 text-sm ${tab===key?"bg-[var(--primary)] text-[var(--background)]":"border border-[var(--border)] text-[var(--muted)]"}`}><Icon size={16}/>{label}</button>)}</div>
  {tab==="customers"&&<section className="mt-4 rounded-2xl border border-[var(--border)] bg-[var(--surface)]"><div className="flex flex-col gap-3 border-b border-[var(--border)] p-4 sm:flex-row sm:items-center sm:justify-between"><h2 className="font-semibold">Unified customer profile index</h2><label className="flex items-center gap-2 rounded-xl border border-[var(--border)] px-3 py-2 text-sm"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search ID, username, name, lifecycle…" className="w-full bg-transparent outline-none sm:w-72"/></label></div><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead><tr className="border-b border-[var(--border)] text-xs text-[var(--muted)]"><th className="p-3">Customer ID</th><th>User</th><th>Lifecycle</th><th>Health</th><th>Risk</th><th>Orders</th><th>Tickets</th><th>Lifetime value</th></tr></thead><tbody>{filtered.map(c=><tr key={c.user_id} className="border-b border-[var(--border)]"><td className="p-3 font-medium">{c.customer_id||"—"}</td><td><div>{c.full_name||c.username||"Unnamed"}</div><div className="text-xs text-[var(--muted)]">{c.username?`@${c.username}`:c.user_id}</div></td><td>{c.lifecycle_stage||"Registered"}</td><td><span className="rounded-full border border-[var(--border)] px-2 py-1 text-xs">{c.health_state||"Stable"} · {Number(c.health_score||0).toFixed(0)}</span></td><td>{c.churn_risk==null?"—":`${Number(c.churn_risk).toFixed(0)}%`}</td><td>{c.order_count??0}</td><td>{c.open_ticket_count??0}</td><td>{Number(c.lifetime_order_value||0).toFixed(2)} {"USD"}</td></tr>)}</tbody></table>{filtered.length===0&&<p className="p-8 text-sm text-[var(--muted)]">No customers match the search.</p>}</div></section>}
  {tab==="support"&&<section className="mt-4 rounded-2xl border border-[var(--border)] bg-[var(--surface)]"><div className="border-b border-[var(--border)] p-4"><h2 className="font-semibold">Support operations queue</h2><p className="mt-1 text-sm text-[var(--muted)]">Tickets use the existing DRIGHT chat architecture through conversation_id; CRM stores workflow and SLA metadata only.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead><tr className="border-b border-[var(--border)] text-xs text-[var(--muted)]"><th className="p-3">Ticket</th><th>Subject</th><th>Category</th><th>Priority</th><th>Status</th><th>Created</th></tr></thead><tbody>{tickets.map(t=><tr key={t.id} className="border-b border-[var(--border)]"><td className="p-3 font-medium">{t.ticket_id}</td><td>{t.subject}</td><td>{t.category}</td><td>{t.priority}</td><td>{t.status}</td><td>{new Date(t.created_at).toLocaleString()}</td></tr>)}</tbody></table>{tickets.length===0&&<p className="p-8 text-sm text-[var(--muted)]">No support tickets yet.</p>}</div></section>}
  {tab==="sales"&&<section className="mt-4 rounded-2xl border border-[var(--border)] bg-[var(--surface)]"><div className="border-b border-[var(--border)] p-4"><h2 className="font-semibold">Sales pipeline</h2><p className="mt-1 text-sm text-[var(--muted)]">Marketplace sales remain authoritative in orders/transactions. This pipeline is for configured business, advertising, partnership and enterprise workflows.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead><tr className="border-b border-[var(--border)] text-xs text-[var(--muted)]"><th className="p-3">Lead</th><th>Organization</th><th>Contact</th><th>Stage</th><th>Value</th><th>Next action</th></tr></thead><tbody>{leads.map(l=><tr key={l.id} className="border-b border-[var(--border)]"><td className="p-3 font-medium">{l.lead_id}</td><td>{l.organization_name||"—"}</td><td>{l.contact_name||"—"}</td><td>{l.stage}</td><td>{l.value_estimate==null?"—":`${Number(l.value_estimate).toFixed(2)} ${l.currency_code||"USD"}`}</td><td>{l.next_action||"—"}</td></tr>)}</tbody></table>{leads.length===0&&<p className="p-8 text-sm text-[var(--muted)]">No sales leads yet.</p>}</div></section>}
 </main>;
}
