"use client";

import { useEffect, useState } from "react";
import { Gift, TicketPercent, Trophy, Coins, Plus, RefreshCw } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Coupon={id:string;coupon_id:string;code:string;coupon_type:string;discount_value:number;status:string;total_uses:number;maximum_total_uses:number|null};
type Giveaway={id:string;giveaway_id:string;title:string;status:string;start_at:string;end_at:string;winner_user_id:string|null};

export default function AdminRewardsPage(){
 const supabase=createClient(); const [coupons,setCoupons]=useState<Coupon[]>([]); const [giveaways,setGiveaways]=useState<Giveaway[]>([]); const [stats,setStats]=useState({credits:0,tokens:0,redemptions:0,entries:0}); const [msg,setMsg]=useState("");
 const [coupon,setCoupon]=useState({code:"",type:"percentage",value:"",min:"",maxUses:"",expires:""});
 async function load(){const [c,g,rt,ce]=await Promise.all([supabase.from("coupons").select("id,coupon_id,code,coupon_type,discount_value,status,total_uses,maximum_total_uses").order("created_at",{ascending:false}),supabase.from("giveaway_campaigns").select("id,giveaway_id,title,status,start_at,end_at,winner_user_id").order("created_at",{ascending:false}),supabase.from("reward_transactions").select("reward_type,amount,transaction_type"),supabase.from("giveaway_entries").select("id",{count:"exact",head:true})]); let credits=0,tokens=0;(rt.data??[]).forEach((r:any)=>{if(r.transaction_type==='issue'&&r.reward_type==='promotion_credit')credits+=Number(r.amount);if(r.transaction_type==='issue'&&r.reward_type==='promotion_token')tokens+=Number(r.amount)}); const cr=await supabase.from("coupon_redemptions").select("id",{count:"exact",head:true}); setCoupons(c.data??[]);setGiveaways(g.data??[]);setStats({credits,tokens,redemptions:cr.count??0,entries:ce.count??0});}
 useEffect(()=>{load()},[]);
 async function createCoupon(){setMsg("");const {data:{user}}=await supabase.auth.getUser();if(!user)return;const value=Number(coupon.value);const {error}=await supabase.from("coupons").insert({code:coupon.code.trim().toUpperCase(),coupon_type:coupon.type,discount_value:value,minimum_order_value:Number(coupon.min||0),maximum_total_uses:coupon.maxUses?Number(coupon.maxUses):null,expires_at:coupon.expires||null,status:"active",created_by:user.id});setMsg(error?error.message:"Coupon created.");if(!error){setCoupon({code:"",type:"percentage",value:"",min:"",maxUses:"",expires:""});load();}}
 async function issue(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;const target=prompt("User UUID to reward");if(!target)return;const type=prompt("Reward type: promotion_credit or promotion_token","promotion_credit");if(!type)return;const amount=Number(prompt("Amount","10"));if(!amount)return;const {error}=await supabase.rpc("issue_reward",{p_user_id:target,p_reward_type:type,p_amount:amount,p_reason:"Admin-issued promotional reward",p_source_type:"admin"});setMsg(error?.message??"Reward issued.");if(!error)load();}
 async function pickWinner(id:string){const {data,error}=await supabase.rpc("select_giveaway_winner",{p_giveaway_id:id});setMsg(error?.message??`Winner selected: ${data?.winner_user_id??"—"}`);load();}
 return <div className="mx-auto max-w-7xl px-4 py-7 sm:px-6 lg:px-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-widest text-[var(--muted)]">Promotion economy</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Coupons & Rewards</h1><p className="mt-2 text-sm text-[var(--muted)]">Control promotional value without touching DRIGHT&apos;s authoritative cash ledger.</p></div><button onClick={()=>{load()}} className="inline-flex items-center gap-2 rounded-xl border border-[var(--border)] px-4 py-2.5 text-sm"><RefreshCw size={16}/>Refresh</button></div>
 <section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><TicketPercent size={20}/><p className="mt-4 text-sm text-[var(--muted)]">Coupon redemptions</p><p className="text-2xl font-semibold">{stats.redemptions}</p></div><div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><Coins size={20}/><p className="mt-4 text-sm text-[var(--muted)]">Credits issued</p><p className="text-2xl font-semibold">{stats.credits}</p></div><div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><Gift size={20}/><p className="mt-4 text-sm text-[var(--muted)]">Tokens issued</p><p className="text-2xl font-semibold">{stats.tokens}</p></div><div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><Trophy size={20}/><p className="mt-4 text-sm text-[var(--muted)]">Giveaway entries</p><p className="text-2xl font-semibold">{stats.entries}</p></div></section>
 <section className="mt-8 grid gap-6 lg:grid-cols-2"><article className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6"><div className="flex items-center justify-between"><h2 className="font-semibold">Create coupon</h2><Plus size={18}/></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><input value={coupon.code} onChange={e=>setCoupon({...coupon,code:e.target.value})} placeholder="Coupon code" className="rounded-xl border border-[var(--border)] bg-[var(--background)] px-4 py-3 text-sm"/><select value={coupon.type} onChange={e=>setCoupon({...coupon,type:e.target.value})} className="rounded-xl border border-[var(--border)] bg-[var(--background)] px-4 py-3 text-sm"><option value="percentage">Percentage</option><option value="fixed">Fixed</option></select><input value={coupon.value} onChange={e=>setCoupon({...coupon,value:e.target.value})} placeholder="Discount value" type="number" min="1" max={coupon.type==='percentage'?100:undefined} className="rounded-xl border border-[var(--border)] bg-[var(--background)] px-4 py-3 text-sm"/><input value={coupon.min} onChange={e=>setCoupon({...coupon,min:e.target.value})} placeholder="Minimum order" type="number" min="0" className="rounded-xl border border-[var(--border)] bg-[var(--background)] px-4 py-3 text-sm"/><input value={coupon.maxUses} onChange={e=>setCoupon({...coupon,maxUses:e.target.value})} placeholder="Maximum uses" type="number" min="1" className="rounded-xl border border-[var(--border)] bg-[var(--background)] px-4 py-3 text-sm"/><input value={coupon.expires} onChange={e=>setCoupon({...coupon,expires:e.target.value})} type="datetime-local" className="rounded-xl border border-[var(--border)] bg-[var(--background)] px-4 py-3 text-sm"/></div><button onClick={createCoupon} className="mt-4 w-full rounded-xl bg-[var(--primary)] px-4 py-3 text-sm font-medium text-[var(--primary-contrast)]">Create coupon</button></article>
 <article className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6"><h2 className="font-semibold">Issue promotional reward</h2><p className="mt-2 text-sm text-[var(--muted)]">Credits and tokens remain separate from withdrawable cash.</p><button onClick={issue} className="mt-5 rounded-xl border border-[var(--border)] px-4 py-3 text-sm font-medium">Issue reward</button>{msg&&<p className="mt-4 text-sm text-[var(--muted)]">{msg}</p>}</article></section>
 <section className="mt-8 grid gap-6 lg:grid-cols-2"><article className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6"><h2 className="font-semibold">Coupons</h2><div className="mt-4 space-y-2">{coupons.map(c=><div key={c.id} className="flex items-center justify-between rounded-xl border border-[var(--border)] p-4"><div><p className="font-semibold">{c.code}</p><p className="text-xs text-[var(--muted)]">{c.discount_value}{c.coupon_type==='percentage'?"%":""} · {c.status}</p></div><span className="text-xs text-[var(--muted)]">{c.total_uses}{c.maximum_total_uses?` / ${c.maximum_total_uses}`:" uses"}</span></div>)}</div></article><article className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6"><h2 className="font-semibold">Giveaways</h2><div className="mt-4 space-y-2">{giveaways.map(g=><div key={g.id} className="flex items-center justify-between gap-3 rounded-xl border border-[var(--border)] p-4"><div><p className="font-semibold">{g.title}</p><p className="text-xs text-[var(--muted)]">{g.status}</p></div>{g.status==='active'&&<button onClick={()=>pickWinner(g.id)} className="rounded-lg border border-[var(--border)] px-3 py-2 text-xs">Select winner</button>}</div>)}</div></article></section></div>;
}
