"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { BriefcaseBusiness, Bookmark, FileText, Plus, Search } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { JobCard, Job } from "@/components/jobs/job-card";

type ApplicationRow = { id: string; universal_id: string; job_id: string; status: string; created_at: string; job?: Job };

export function MyJobsWorkspace() {
  const supabase = useMemo(() => createClient(), []);
  const [jobs, setJobs] = useState<Job[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { let cancelled = false; (async () => { const { data: auth } = await supabase.auth.getUser(); if (!auth.user) { if (!cancelled) setLoading(false); return; } const { data, error: queryError } = await supabase.from("jobs").select("id,universal_id,employer_id,title,description,category,location_city,location_region,location_country,work_mode,employment_type,salary_min,salary_max,currency_code,experience_level,deadline,status,created_at").eq("employer_id", auth.user.id).order("created_at", { ascending: false }); if (!cancelled) { setJobs((data ?? []) as Job[]); setError(queryError?.message || ""); setLoading(false); } })(); return () => { cancelled = true; }; }, [supabase]);
  return <WorkspaceShell title="My Jobs" subtitle="Manage jobs posted from your existing DRIGHT identity." actionHref="/jobs/post" actionLabel="Post a job" icon={BriefcaseBusiness}>{loading ? <Skeleton/> : error ? <ErrorBox text={error}/> : jobs.length === 0 ? <Empty icon={Plus} title="No jobs yet" text="Create your first job listing when you are ready."/> : <div className="grid gap-5 sm:grid-cols-2">{jobs.map((job) => <JobCard key={job.id} job={job}/>)}</div>}</WorkspaceShell>;
}

export function ApplicationsWorkspace() {
  const supabase = useMemo(() => createClient(), []);
  const [rows, setRows] = useState<ApplicationRow[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { let cancelled = false; (async () => { const { data: auth } = await supabase.auth.getUser(); if (!auth.user) { if (!cancelled) setLoading(false); return; } const { data, error: queryError } = await supabase.from("job_applications").select("id,universal_id,job_id,status,created_at").eq("applicant_id", auth.user.id).order("created_at", { ascending: false }); const applications = (data ?? []) as ApplicationRow[]; if (applications.length) { const { data: jobs } = await supabase.from("jobs").select("id,universal_id,employer_id,title,description,category,location_city,location_region,location_country,work_mode,employment_type,salary_min,salary_max,currency_code,experience_level,deadline,status,created_at").in("id", applications.map((row) => row.job_id)); const map = new Map((jobs ?? []).map((job) => [job.id, job as Job])); applications.forEach((row) => { row.job = map.get(row.job_id); }); } if (!cancelled) { setRows(applications); setError(queryError?.message || ""); setLoading(false); } })(); return () => { cancelled = true; }; }, [supabase]);
  return <WorkspaceShell title="Applications" subtitle="Track the real applications attached to your DRIGHT account." actionHref="/jobs" actionLabel="Find jobs" icon={FileText}>{loading ? <Skeleton/> : error ? <ErrorBox text={error}/> : rows.length === 0 ? <Empty icon={Search} title="No applications yet" text="Applications you submit on DRIGHT will appear here."/> : <div className="space-y-3">{rows.map((row) => <Link key={row.id} href={`/jobs/${row.job_id}`} className="block rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-[var(--shadow-sm)]"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">{row.job?.title || "Unavailable job"}</h2><p className="mt-1 font-mono text-[10px] text-[var(--muted)]">{row.universal_id}</p></div><span className="w-fit rounded-full bg-[var(--background)] px-3 py-1.5 text-xs font-semibold capitalize">{row.status.replace(/_/g, " ")}</span></div><p className="mt-3 text-xs text-[var(--muted)]">Applied {new Date(row.created_at).toLocaleDateString()}</p></Link>)}</div>}</WorkspaceShell>;
}

export function SavedJobsWorkspace() {
  const supabase = useMemo(() => createClient(), []);
  const [jobs, setJobs] = useState<Job[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { let cancelled = false; (async () => { const { data: auth } = await supabase.auth.getUser(); if (!auth.user) { if (!cancelled) setLoading(false); return; } const { data: savedRows, error: savedError } = await supabase.from("saved_jobs").select("job_id").eq("user_id", auth.user.id).order("created_at", { ascending: false }); const ids = (savedRows ?? []).map((row) => row.job_id as string); const { data } = ids.length ? await supabase.from("jobs").select("id,universal_id,employer_id,title,description,category,location_city,location_region,location_country,work_mode,employment_type,salary_min,salary_max,currency_code,experience_level,deadline,status,created_at").in("id", ids) : { data: [] as Job[] }; const byId = new Map((data ?? []).map((job) => [job.id, job as Job])); if (!cancelled) { setJobs(ids.map((id) => byId.get(id)).filter((job): job is Job => Boolean(job))); setError(savedError?.message || ""); setLoading(false); } })(); return () => { cancelled = true; }; }, [supabase]);
  return <WorkspaceShell title="Saved Jobs" subtitle="Your saved-job list uses the existing DRIGHT saved job records." actionHref="/jobs" actionLabel="Browse jobs" icon={Bookmark}>{loading ? <Skeleton/> : error ? <ErrorBox text={error}/> : jobs.length === 0 ? <Empty icon={Bookmark} title="Nothing saved yet" text="Save jobs from the marketplace to return to them later."/> : <div className="grid gap-5 sm:grid-cols-2">{jobs.map((job) => <JobCard key={job.id} job={job}/>)}</div>}</WorkspaceShell>;
}

function WorkspaceShell({ title, subtitle, actionHref, actionLabel, icon: Icon, children }: { title: string; subtitle: string; actionHref: string; actionLabel: string; icon: typeof Bookmark; children: React.ReactNode }) { return <div className="dright-page mx-auto max-w-6xl"><section className="mb-7 rounded-[2rem] border border-[var(--border)] bg-[var(--surface)] p-6 shadow-[var(--shadow-md)] sm:p-9"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><div className="inline-flex items-center gap-2 rounded-full bg-[var(--background)] px-3 py-1.5 text-xs font-semibold text-[var(--muted)]"><Icon size={14}/> Jobs workspace</div><h1 className="mt-4 text-3xl font-semibold tracking-tight">{title}</h1><p className="mt-2 text-sm text-[var(--muted)]">{subtitle}</p></div><Link href={actionHref} className="inline-flex w-fit items-center gap-2 rounded-xl bg-[var(--primary)] px-4 py-2.5 text-sm font-semibold text-[var(--background)]">{actionLabel}</Link></div></section>{children}</div>; }
function Skeleton(){return <div className="grid gap-5 sm:grid-cols-2">{Array.from({length:4}).map((_,i)=><div key={i} className="h-64 animate-pulse rounded-2xl border border-[var(--border)] bg-[var(--surface)]"/>)}</div>}
function ErrorBox({text}:{text:string}){return <div className="rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-700">{text}</div>}
function Empty({icon:Icon,title,text}:{icon:typeof Bookmark;title:string;text:string}){return <div className="rounded-2xl border border-dashed border-[var(--border)] bg-[var(--surface)] p-10 text-center"><Icon size={26} className="mx-auto text-[var(--muted)]"/><h2 className="mt-3 font-semibold">{title}</h2><p className="mt-1 text-sm text-[var(--muted)]">{text}</p></div>}
