"use client";

import { useEffect, useState } from "react";
import { Gift, Coins, TicketPercent, Trophy, Copy, Check, Clock3 } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Wallet = { promotion_credit_balance: number; promotion_token_balance: number; reward_wallet_id: string };
type Coupon = { id:string; coupon_id:string; code:string; coupon_type:string; discount_value:number; expires_at:string|null; maximum_discount:number|null };
type Voucher = { voucher_id:string; voucher_type:string; value:number; currency_code:string|null; expires_at:string|null; status:string };
type Giveaway = { id:string; giveaway_id:string; title:string; description:string|null; reward:any; start_at:string; end_at:string; status:string };

export default function RewardsPage(){
 const supabase=createClient(); const [wallet,setWallet]=useState<Wallet|null>(null); const [coupons,setCoupons]=useState<Coupon[]>([]); const [vouchers,setVouchers]=useState<Voucher[]>([]); const [giveaways,setGiveaways]=useState<Giveaway[]>([]); const [giftCode,setGiftCode]=useState(""); const [message,setMessage]=useState(""); const [copied,setCopied]=useState("");
 async function load(){ const {data:{user}}=await supabase.auth.getUser(); if(!user)return; const [w,c,v,g]=await Promise.all([supabase.from("reward_wallets").select("reward_wallet_id,promotion_credit_balance,promotion_token_balance").eq("user_id",user.id).maybeSingle(),supabase.from("coupons").select("id,coupon_id,code,coupon_type,discount_value,expires_at,maximum_discount").eq("status","active").order("expires_at",{ascending:true}),supabase.from("vouchers").select("voucher_id,voucher_type,value,currency_code,expires_at,status").eq("user_id",user.id).order("issued_at",{ascending:false}),supabase.from("giveaway_campaigns").select("id,giveaway_id,title,description,reward,start_at,end_at,status").in("status",["scheduled","active"]).order("start_at",{ascending:true})]); setWallet(w.data??null); setCoupons(c.data??[]); setVouchers(v.data??[]); setGiveaways(g.data??[]); }
 useEffect(()=>{load()},[]);
 async function redeemGift(){setMessage(""); const {data:{user}}=await supabase.auth.getUser(); if(!user||!giftCode.trim())return; const {data,error}=await supabase.rpc("redeem_gift_code",{p_code:giftCode,p_user_id:user.id}); if(error)setMessage(error.message); else {setMessage(`Gift code redeemed: ${data.value} ${data.currency_code}`);setGiftCode("");load();}}
 async function enter(id:string){const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data,error}=await supabase.rpc("enter_giveaway",{p_giveaway_id:id,p_user_id:user.id});setMessage(error?.message??(data?.already_entered?"You are already entered.":"Entry recorded."));}
 async function copy(code:string){await navigator.clipboard?.writeText(code);setCopied(code);setTimeout(()=>setCopied(""),1500)}
 return <div className="mx-auto max-w-7xl px-4 py-7 sm:px-6 lg:px-8"><div><p className="text-xs font-semibold uppercase tracking-widest text-[var(--muted)]">Rewards & incentives</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Your Reward Center</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--muted)]">Keep promotional value separate from cash. Credits and tokens are non-withdrawable unless DRIGHT explicitly configures a financial rule.</p></div>
 <section className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6"><Coins size={22}/><p className="mt-4 text-sm text-[var(--muted)]">Promotion credits</p><p className="mt-1 text-3xl font-semibold">{wallet?.promotion_credit_balance??0}</p></div><div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6"><Gift size={22}/><p className="mt-4 text-sm text-[var(--muted)]">Promotion tokens</p><p className="mt-1 text-3xl font-semibold">{wallet?.promotion_token_balance??0}</p></div><div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6"><TicketPercent size={22}/><p className="mt-4 text-sm text-[var(--muted)]">Available coupons</p><p className="mt-1 text-3xl font-semibold">{coupons.length}</p></div></section>
 <section className="mt-8 grid gap-6 lg:grid-cols-2"><article className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6"><div className="flex items-center gap-3"><TicketPercent size={20}/><h2 className="font-semibold">Coupons</h2></div><div className="mt-4 space-y-3">{coupons.length===0?<p className="text-sm text-[var(--muted)]">No active coupons are available.</p>:coupons.map(c=><div key={c.id} className="flex items-center justify-between gap-4 rounded-xl border border-[var(--border)] p-4"><div><p className="font-semibold">{c.code}</p><p className="text-sm text-[var(--muted)]">{c.coupon_type==='percentage'?`${c.discount_value}% off`:`${c.discount_value} off`}{c.maximum_discount?` · max ${c.maximum_discount}`:""}</p>{c.expires_at&&<p className="mt-1 flex items-center gap-1 text-xs text-[var(--muted)]"><Clock3 size={13}/>Expires {new Date(c.expires_at).toLocaleDateString()}</p>}</div><button onClick={()=>copy(c.code)} className="rounded-xl border border-[var(--border)] p-2" aria-label="Copy coupon code">{copied===c.code?<Check size={17}/>:<Copy size={17}/>}</button></div>)}</div></article>
 <article className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6"><div className="flex items-center gap-3"><Gift size={20}/><h2 className="font-semibold">Vouchers</h2></div><div className="mt-4 space-y-3">{vouchers.length===0?<p className="text-sm text-[var(--muted)]">No vouchers yet.</p>:vouchers.map(v=><div key={v.voucher_id} className="rounded-xl border border-[var(--border)] p-4"><div className="flex justify-between"><p className="font-medium">{v.voucher_type.replaceAll("_"," ")}</p><span className="text-xs capitalize text-[var(--muted)]">{v.status}</span></div><p className="mt-1 text-2xl font-semibold">{v.value}{v.currency_code?` ${v.currency_code}`:""}</p>{v.expires_at&&<p className="mt-1 text-xs text-[var(--muted)]">Expires {new Date(v.expires_at).toLocaleDateString()}</p>}</div>)}</div></article></section>
 <section className="mt-6 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6"><h2 className="font-semibold">Redeem a gift code</h2><div className="mt-4 flex flex-col gap-3 sm:flex-row"><input value={giftCode} onChange={e=>setGiftCode(e.target.value)} placeholder="Enter gift code" className="min-w-0 flex-1 rounded-xl border border-[var(--border)] bg-[var(--background)] px-4 py-3 text-sm outline-none"/><button onClick={redeemGift} className="rounded-xl bg-[var(--primary)] px-5 py-3 text-sm font-medium text-[var(--primary-contrast)]">Redeem</button></div>{message&&<p className="mt-3 text-sm text-[var(--muted)]">{message}</p>}</section>
 <section className="mt-6"><div className="flex items-center gap-3"><Trophy size={20}/><h2 className="text-xl font-semibold">Giveaways</h2></div><div className="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{giveaways.length===0?<p className="text-sm text-[var(--muted)]">No active giveaways right now.</p>:giveaways.map(g=><article key={g.id} className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><p className="text-xs uppercase tracking-widest text-[var(--muted)]">{g.status}</p><h3 className="mt-2 font-semibold">{g.title}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{g.description||"Join this DRIGHT incentive campaign."}</p><p className="mt-4 text-sm">Ends {new Date(g.end_at).toLocaleDateString()}</p><button onClick={()=>enter(g.id)} className="mt-4 w-full rounded-xl border border-[var(--border)] px-4 py-2.5 text-sm font-medium hover:bg-[var(--background)]">Enter giveaway</button></article>)}</div></section></div>;
}