"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, Loader2, ShieldCheck, XCircle } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

export default function AdministratorsPage(){
 const supabase=createClient(); const [requests,setRequests]=useState<any[]>([]); const [roles,setRoles]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [busy,setBusy]=useState<string|null>(null); const [reason,setReason]=useState<Record<string,string>>({});
 async function load(){setLoading(true);const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href="/login?next=/admin/administrators";return;}const {data:ok}=await supabase.rpc("admin_has_permission",{p_permission:"admins.manage",p_user_id:user.id});if(!ok){setError("You do not have permission to manage administrators.");setLoading(false);return;}const [{data:r,error:re},{data:rolesData}]=await Promise.all([supabase.from("admin_access_requests").select("id,request_id,applicant_user_id,requested_role_id,status,reason,agreement_version,submitted_at,review_notes").order("submitted_at",{ascending:false}),supabase.from("roles").select("id,name,slug").eq("is_system_role",false).eq("is_active",true).order("name")]);if(re)setError(re.message);setRequests(r||[]);setRoles(rolesData||[]);setLoading(false);}
 useEffect(()=>{load();},[]);
 async function review(id:string,decision:string){setBusy(id);const {error:e}=await supabase.rpc("admin_review_access_request",{p_request_id:id,p_decision:decision,p_notes:reason[id]||null});if(e)setError(e.message);else await load();setBusy(null);}
 if(error&&!requests.length&&!loading)return <main className="mx-auto max-w-xl px-4 py-16 text-center"><ShieldCheck className="mx-auto" size={40}/><h1 className="mt-4 text-2xl font-semibold">Access restricted</h1><p className="mt-2 text-sm text-[var(--muted)]">{error}</p></main>;
 return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><p className="text-xs font-semibold uppercase tracking-widest text-[var(--muted)]">Governance · Access</p><h1 className="mt-1 text-3xl font-semibold">Administrator Activation</h1><p className="mt-2 text-sm text-[var(--muted)]">Review administrator access requests before activating custom administrative authority.</p>{error&&<p className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<section className="mt-6 overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--surface)]">{loading?<div className="p-8 text-sm text-[var(--muted)]">Loading requests…</div>:requests.length===0?<div className="p-8 text-sm text-[var(--muted)]">No administrator access requests.</div>:<div className="divide-y divide-[var(--border)]">{requests.map(r=>{const role=roles.find(x=>x.id===r.requested_role_id);return <div key={r.id} className="p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="font-semibold">{role?.name||"Administrator role"}</span><span className="rounded-full border border-[var(--border)] px-2 py-1 text-[10px] uppercase">{r.status}</span></div><p className="mt-2 font-mono text-xs text-[var(--muted)]">{r.request_id}</p><p className="mt-2 text-xs text-[var(--muted)]">Applicant: {r.applicant_user_id}</p><p className="mt-1 text-xs text-[var(--muted)]">Submitted: {new Date(r.submitted_at).toLocaleString()}</p>{r.reason&&<p className="mt-3 text-sm">{r.reason}</p>}</div>{r.status==='pending'&&<div className="flex flex-col gap-2 sm:flex-row"><input value={reason[r.request_id]||""} onChange={e=>setReason(x=>({...x,[r.request_id]:e.target.value}))} placeholder="Review note" className="rounded-xl border border-[var(--border)] bg-[var(--background)] px-3 py-2 text-sm"/><button disabled={busy===r.request_id} onClick={()=>review(r.request_id,'approved')} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[var(--primary)] px-3 py-2 text-sm font-semibold text-[var(--background)]">{busy===r.request_id?<Loader2 className="animate-spin" size={15}/>:<CheckCircle2 size={15}/>}Approve</button><button disabled={busy===r.request_id} onClick={()=>review(r.request_id,'rejected')} className="inline-flex items-center justify-center gap-2 rounded-xl border border-[var(--border)] px-3 py-2 text-sm font-semibold"><XCircle size={15}/>Reject</button></div>}</div></div>})}</div>}</section></main>;
}
