"use client";

import { useEffect, useMemo, useState } from "react";
import { Trophy, Medal } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Row={user_id:string;display_name:string|null;username:string|null;avatar_url:string|null;score:number;rank:number};
const types=[['creator','Top creators'],['affiliate','Top affiliates'],['seller','Top sellers'],['community','Top community contributors']];

export default function LeaderboardsPage(){
 const supabase=useMemo(()=>createClient(),[]);const [type,setType]=useState('creator');const [rows,setRows]=useState<Row[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 useEffect(()=>{let cancelled=false;(async()=>{setLoading(true);const {data,error:e}=await supabase.rpc('get_social_leaderboard',{p_type:type,p_community_id:null,p_limit:50});if(!cancelled){setRows((data||[]) as Row[]);setError(e?.message||'');setLoading(false);}})();return()=>{cancelled=true};},[type,supabase]);
 return <main className="mx-auto max-w-5xl px-4 py-7 sm:px-6"><section className="rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-6 sm:p-8"><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[var(--background)]"><Trophy/></div><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--muted)]">DRIGHT Rankings</p><h1 className="text-3xl font-bold">Leaderboards</h1></div></div><p className="mt-4 max-w-3xl text-sm leading-6 text-[var(--muted)]">Rankings use authoritative platform activity. Private wallet balances, KYC data and exact earnings are never exposed as leaderboard metrics.</p><div className="mt-6 flex flex-wrap gap-2">{types.map(([value,label])=><button key={value} onClick={()=>setType(value)} className={`rounded-xl border px-4 py-2 text-xs font-semibold ${type===value?'border-[var(--primary)] bg-[var(--primary)] text-[var(--primary-contrast)]':'border-[var(--border)] text-[var(--muted)]'}`}>{label}</button>)}</div></section><section className="mt-6 overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--surface)]">{error?<p className="p-8 text-sm text-[var(--muted)]">{error}</p>:loading?Array.from({length:8}).map((_,i)=><div key={i} className="h-16 animate-pulse border-b border-[var(--border)]"/>):rows.length===0?<p className="p-10 text-center text-sm text-[var(--muted)]">No public ranking data yet.</p>:rows.map((r,i)=><div key={r.user_id} className="flex items-center gap-4 border-b border-[var(--border)] p-4 last:border-0"><div className="grid h-9 w-9 place-items-center rounded-full bg-[var(--background)] text-sm font-bold">{r.rank<=3?<Medal size={17}/>:r.rank}</div><div className="grid h-10 w-10 place-items-center rounded-full bg-[var(--background)] text-xs font-bold">{(r.username||r.display_name||'D').slice(0,1).toUpperCase()}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{r.display_name||r.username||'DRIGHT user'}</p><p className="truncate text-xs text-[var(--muted)]">@{r.username||'user'}</p></div><span className="text-sm font-semibold">{Number(r.score).toLocaleString()}</span></div>)}</section></main>;
}
