"use client";

import { FormEvent, useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { LifeBuoy, Plus, RefreshCw } from "lucide-react";

const supabase=createClient();
export default function SupportPage(){
 const [userId,setUserId]=useState<string>(""); const [tickets,setTickets]=useState<any[]>([]); const [subject,setSubject]=useState(""); const [category,setCategory]=useState("general"); const [priority,setPriority]=useState("normal"); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){location.href="/login?next=/support";return;}setUserId(user.id);const {data,error}=await supabase.from("crm_support_tickets").select("id,ticket_id,subject,category,priority,status,created_at,updated_at").eq("customer_user_id",user.id).order("created_at",{ascending:false});if(error)setError(error.message);else setTickets(data||[])}
 useEffect(()=>{load()},[]);
 async function createTicket(e:FormEvent){e.preventDefault();if(!subject.trim())return;setBusy(true);setError("");const {data,error}=await supabase.from("crm_support_tickets").insert({customer_user_id:userId,subject:subject.trim(),category,priority,status:"new"}).select("id,ticket_id,subject,category,priority,status,created_at,updated_at").single();if(error)setError(error.message);else{setTickets(v=>[data,...v]);setSubject("")}setBusy(false)}
 return <main className="mx-auto max-w-5xl p-4 sm:p-6 lg:p-8"><header className="rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-6"><div className="flex items-start gap-4"><div className="rounded-2xl border border-[var(--border)] p-3"><LifeBuoy/></div><div><p className="text-xs font-semibold uppercase tracking-widest text-[var(--muted)]">DRIGHT Support</p><h1 className="mt-1 text-3xl font-semibold">Customer Support Center</h1><p className="mt-2 text-sm text-[var(--muted)]">Create and track support requests. Internal notes and restricted administrative information remain private.</p></div></div></header>
 <section className="mt-6 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><h2 className="font-semibold">New support request</h2><form onSubmit={createTicket} className="mt-4 grid gap-3 sm:grid-cols-2"><input required value={subject} onChange={e=>setSubject(e.target.value)} placeholder="What do you need help with?" className="rounded-xl border border-[var(--border)] bg-transparent px-3 py-3 sm:col-span-2"/><select value={category} onChange={e=>setCategory(e.target.value)} className="rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 py-3"><option value="general">General</option><option value="billing">Billing</option><option value="payment">Payment</option><option value="vendor">Vendor</option><option value="affiliate">Affiliate</option><option value="technical">Technical</option><option value="security">Security</option></select><select value={priority} onChange={e=>setPriority(e.target.value)} className="rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 py-3"><option value="normal">Normal</option><option value="low">Low</option><option value="high">High</option><option value="urgent">Urgent</option></select><button disabled={busy} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[var(--primary)] px-4 py-3 text-sm font-semibold text-[var(--background)] sm:col-span-2"><Plus size={17}/>{busy?"Creating…":"Create ticket"}</button></form>{error&&<p className="mt-3 text-sm text-red-500">{error}</p>}</section>
 <section className="mt-6 rounded-2xl border border-[var(--border)] bg-[var(--surface)]"><div className="flex items-center justify-between border-b border-[var(--border)] p-5"><div><h2 className="font-semibold">My tickets</h2><p className="mt-1 text-sm text-[var(--muted)]">Ticket IDs are stable and can be shared with DRIGHT Support.</p></div><button onClick={load} className="rounded-xl border border-[var(--border)] p-2" title="Refresh"><RefreshCw size={16}/></button></div><div className="divide-y divide-[var(--border)]">{tickets.map(t=><article key={t.id} className="p-5"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold text-[var(--muted)]">{t.ticket_id}</p><h3 className="mt-1 font-semibold">{t.subject}</h3><p className="mt-1 text-xs text-[var(--muted)]">{t.category} · {t.priority} · {t.status}</p></div><p className="text-xs text-[var(--muted)]">{new Date(t.created_at).toLocaleString()}</p></div></article>)}{tickets.length===0&&<p className="p-8 text-sm text-[var(--muted)]">You have no support tickets.</p>}</div></section>
 </main>;
}
