"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, LockKeyhole, ShoppingBag } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Row={id:string;quantity:number;unit_price:number;currency:string|null;marketplace_item_id:string;item?:{id:string;title:string;item_type:string|null}};

export default function CheckoutPage(){
 const supabase=createClient(); const [rows,setRows]=useState<Row[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [submitting,setSubmitting]=useState(false); const [created,setCreated]=useState("");
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href="/login?next=/checkout";return} const {data:cart,e}=await supabase.from("carts").select("id").eq("user_id",user.id).maybeSingle();if(e||!cart){setError(e?.message||"Your cart is empty.");setLoading(false);return} const r=await supabase.from("cart_items").select("id,quantity,unit_price,currency,marketplace_item_id,marketplace_items(id,title,item_type)").eq("cart_id",cart.id);if(r.error)setError(r.error.message);else setRows((r.data||[]).map((x:any)=>({...x,item:x.marketplace_items})));setLoading(false)})()},[]);
 const currencies=[...new Set(rows.map(r=>r.currency||"USD"))]; const subtotal=rows.reduce((s,r)=>s+(Number(r.unit_price)||0)*r.quantity,0);
 async function placeOrder(){setSubmitting(true);setError(""); const {data:{user}}=await supabase.auth.getUser(); if(!user){setError("Please sign in again.");setSubmitting(false);return} if(currencies.length!==1){setError("Your cart contains multiple currencies. Please purchase these items separately.");setSubmitting(false);return}
   const order=await supabase.from("orders").insert({buyer_id:user.id,status:"pending",currency:currencies[0]||"USD",total_amount:subtotal}).select("id").single();
   if(order.error){setError(order.error.message);setSubmitting(false);return} setCreated(order.data.id);setSubmitting(false);
 }
 if(loading)return <div className="mx-auto max-w-5xl px-4 py-8"><div className="h-80 animate-pulse rounded-[2rem] border border-[var(--border)] bg-[var(--surface)]"/></div>;
 if(created)return <div className="mx-auto max-w-3xl px-4 py-12 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-[var(--background)]"><LockKeyhole size={25}/></div><h1 className="mt-5 text-3xl font-semibold">Order created</h1><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-[var(--muted)]">Your DRIGHT order has been created and is awaiting payment. Payment provider integration will securely authorize and verify the transaction before the order becomes paid.</p><div className="mt-4 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-4 py-3 text-sm">Order ID: <code>{created}</code></div><div className="mt-6 flex justify-center gap-3"><Link href="/orders" className="rounded-xl bg-[var(--primary)] px-5 py-3 text-sm font-semibold text-[var(--background)]">View orders</Link><Link href="/marketplace" className="rounded-xl border border-[var(--border)] px-5 py-3 text-sm font-semibold">Continue shopping</Link></div></div>;
 return <div className="mx-auto max-w-5xl px-4 py-7 sm:px-6 lg:px-8"><Link href="/cart" className="inline-flex items-center gap-2 text-sm font-medium text-[var(--muted)]"><ArrowLeft size={16}/> Back to cart</Link><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_340px]"><section className="rounded-[2rem] border border-[var(--border)] bg-[var(--surface)] p-6 sm:p-8"><div className="flex items-center gap-3"><ShoppingBag size={21}/><div><p className="text-xs font-semibold uppercase tracking-widest text-[var(--muted)]">Checkout</p><h1 className="text-2xl font-semibold">Review your order</h1></div></div><div className="mt-7 space-y-3">{rows.length?rows.map(r=><div key={r.id} className="flex items-center justify-between gap-4 rounded-2xl border border-[var(--border)] p-4"><div className="min-w-0"><p className="truncate font-medium">{r.item?.title||"Listing"}</p><p className="mt-1 text-xs text-[var(--muted)]">{r.item?.item_type||"listing"} · Qty {r.quantity} · ID {r.marketplace_item_id}</p></div><p className="shrink-0 text-sm font-semibold">{r.currency||"USD"} {(r.unit_price*r.quantity).toLocaleString()}</p></div>):<div className="rounded-2xl border border-dashed border-[var(--border)] p-10 text-center text-sm text-[var(--muted)]">Your cart is empty. <Link className="font-semibold underline" href="/marketplace">Browse marketplace</Link></div>}</div>{error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}</section><aside className="h-fit rounded-[2rem] border border-[var(--border)] bg-[var(--surface)] p-6 lg:sticky lg:top-24"><h2 className="font-semibold">Order summary</h2><div className="mt-5 flex justify-between text-sm"><span className="text-[var(--muted)]">Subtotal</span><span>{currencies.length===1?currencies[0]:"—"} {subtotal.toLocaleString()}</span></div><div className="mt-4 flex justify-between border-t border-[var(--border)] pt-4 text-lg font-semibold"><span>Total</span><span>{currencies.length===1?currencies[0]:"—"} {subtotal.toLocaleString()}</span></div><button onClick={placeOrder} disabled={!rows.length||submitting} className="mt-6 w-full rounded-xl bg-[var(--primary)] px-5 py-3.5 text-sm font-semibold text-[var(--background)] disabled:opacity-50">{submitting?"Creating order…":"Continue to secure payment"}</button><p className="mt-4 text-center text-xs leading-5 text-[var(--muted)]">Payment credentials are never collected by this page. Provider authorization and webhook verification will run server-side.</p></aside></div></div>
}
