"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, CheckCircle2, ChevronRight, CreditCard, FileText, LockKeyhole, ReceiptText, ShieldCheck, ShoppingBag, UserRound } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Row={id:string;quantity:number;unit_price:number;currency_code:string;marketplace_item_id:string;item?:{id:string;public_id?:string;title:string;item_type:string|null;price?:number;currency_code?:string}};
type Provider={provider:string;enabled:boolean;mode:string};
const labels:Record<string,string>={paystack:"Paystack",flutterwave:"Flutterwave",wise:"Wise",stripe:"Stripe",coinbase_commerce:"Coinbase Commerce",nowpayments:"NOWPayments"};

export default function CheckoutPage(){
 const supabase=createClient();
 const [rows,setRows]=useState<Row[]>([]); const [cartId,setCartId]=useState(""); const [providers,setProviders]=useState<Provider[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [submitting,setSubmitting]=useState(false); const [paymentUrl,setPaymentUrl]=useState(""); const [orderId,setOrderId]=useState(""); const [email,setEmail]=useState(""); const [userEmail,setUserEmail]=useState("");
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);setError("Sign in to use the current secure checkout. Guest checkout UI is reserved for the guest-payment connector and is not enabled by the current Paystack initializer.");return}setUserEmail(user.email||"");setEmail(user.email||"");const cartResult=await supabase.from("carts").select("id,status").eq("user_id",user.id).eq("status","active").maybeSingle();if(cartResult.error||!cartResult.data){setError(cartResult.error?.message||"Your cart is empty.");setLoading(false);return}setCartId(cartResult.data.id);const r=await supabase.from("cart_items").select("id,quantity,unit_amount,currency_code,item_id,marketplace_items(id,public_id,title,item_type,price,currency_code)").eq("cart_id",cartResult.data.id);if(r.error)setError(r.error.message);else setRows((r.data||[]).map((x:any)=>({id:x.id,quantity:x.quantity,unit_price:Number(x.unit_amount),currency_code:x.currency_code,marketplace_item_id:x.item_id,item:Array.isArray(x.marketplace_items)?x.marketplace_items[0]:x.marketplace_items})));const p=await supabase.from("payment_provider_configs").select("provider,enabled,mode").eq("enabled",true);if(!p.error)setProviders((p.data||[]) as Provider[]);setLoading(false)})()},[]);
 const currencies=useMemo(()=>[...new Set(rows.map(r=>r.currency_code||r.item?.currency_code||"USD"))],[rows]);
 const subtotal=useMemo(()=>rows.reduce((s,r)=>s+(Number(r.item?.price??r.unit_price)||0)*r.quantity,0),[rows]);
 const feeEstimate=0;
 const displayTotal=subtotal+feeEstimate;
 async function payWith(provider:string){if(provider!=="paystack"){setError(`${labels[provider]||provider} is registered but its checkout connector is not live. Paystack is the current launch payment provider.`);return}setSubmitting(true);setError("");const {data:{session}}=await supabase.auth.getSession();if(!session){setError("Your secure session has expired. Sign in again before paying.");setSubmitting(false);return}if(!cartId||!rows.length){setError("Your cart is empty.");setSubmitting(false);return}if(!email.trim()||!email.includes("@")){setError("Enter a valid payment email.");setSubmitting(false);return}if(currencies.length!==1){setError("Your cart contains multiple currencies. Purchase these items separately.");setSubmitting(false);return}const result=await supabase.functions.invoke("paystack-initialize",{body:{cart_id:cartId}});if(result.error){setError(result.error.message||"Unable to start payment.");setSubmitting(false);return}if(result.data?.authorization_url){setOrderId(result.data.public_order_id||result.data.order_id||"");setPaymentUrl(result.data.authorization_url);window.location.href=result.data.authorization_url;return}setError(result.data?.error||"Unable to start payment.");setSubmitting(false)}
 if(loading)return <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8"><div className="h-[620px] animate-pulse rounded-[2rem] border border-[var(--border)] bg-[var(--surface)]"/></div>;
 if(!userEmail)return <div className="mx-auto max-w-3xl px-4 py-14 text-center sm:px-6"><UserRound size={34} className="mx-auto"/><h1 className="mt-5 text-3xl font-bold">Secure checkout requires an account</h1><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-[var(--muted)]">The live Paystack initializer currently requires an authenticated DRIGHT session. This prevents an unsafe client-side payment path. Guest-payment processing must be enabled server-side before it can be offered as a real payment option.</p><Link href="/login?next=/checkout" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[var(--primary)] px-5 py-3 text-sm font-bold text-[var(--background)]">Sign in to checkout <ChevronRight size={16}/></Link><Link href="/marketplace" className="mt-3 block text-sm font-semibold text-[var(--primary)]">Continue shopping</Link></div>;
 if(paymentUrl)return <div className="mx-auto max-w-3xl px-4 py-14 text-center sm:px-6"><div className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-[var(--background)]"><LockKeyhole size={28}/></div><p className="mt-5 text-xs font-bold uppercase tracking-[0.18em] text-[var(--primary)]">Secure payment</p><h1 className="mt-2 text-3xl font-bold">Redirecting to Paystack</h1><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Order <strong>{orderId||"created"}</strong> has been prepared using server-authoritative pricing. Payment credentials are entered only on Paystack&apos;s secure checkout.</p><a href={paymentUrl} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[var(--primary)] px-5 py-3 text-sm font-bold text-[var(--background)]">Continue to Paystack <ChevronRight size={16}/></a><p className="mt-4 text-xs text-[var(--muted)]">Never share your Paystack payment details with DRIGHT support or another user.</p></div>;
 return <div className="mx-auto max-w-6xl px-4 py-7 sm:px-6 lg:px-8">
   <Link href="/cart" className="inline-flex items-center gap-2 text-sm font-medium text-[var(--muted)]"><ArrowLeft size={16}/> Back to cart</Link>
   <div className="mt-5 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--primary)]">Checkout</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Review & pay</h1><p className="mt-2 text-sm text-[var(--muted)]">Clear pricing, secure payment, and a receipt you can reference later.</p></div><div className="flex items-center gap-2 text-xs font-semibold text-[var(--muted)]"><CheckCircle2 size={15}/> Secure session</div></div>
   <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_390px]">
     <main className="space-y-5">
       <section className="rounded-[28px] border border-[var(--border)] bg-[var(--surface)] p-6 shadow-sm sm:p-7"><div className="flex items-center gap-3"><ShoppingBag size={20}/><div><h2 className="font-bold">Your items</h2><p className="mt-1 text-xs text-[var(--muted)]">Product IDs remain visible for support and dispute resolution.</p></div></div><div className="mt-6 space-y-3">{rows.length?rows.map(r=><div key={r.id} className="flex flex-col gap-3 rounded-2xl border border-[var(--border)] p-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><p className="truncate font-semibold">{r.item?.title||"Listing"}</p><p className="mt-1 text-xs text-[var(--muted)]">{r.item?.item_type||"listing"} · Qty {r.quantity} · ID {r.item?.public_id||r.marketplace_item_id}</p></div><p className="shrink-0 text-sm font-bold">{r.currency_code||r.item?.currency_code||"USD"} {(Number(r.item?.price??r.unit_price)*r.quantity).toLocaleString()}</p></div>):<div className="rounded-2xl border border-dashed border-[var(--border)] p-10 text-center text-sm text-[var(--muted)]">Your cart is empty. <Link className="font-semibold underline" href="/marketplace">Browse marketplace</Link></div>}</div></section>
       <section className="rounded-[28px] border border-[var(--border)] bg-[var(--surface)] p-6 shadow-sm sm:p-7"><div className="flex items-center gap-3"><UserRound size={20}/><div><h2 className="font-bold">Buyer details</h2><p className="mt-1 text-xs text-[var(--muted)]">Used for payment receipt and order communication.</p></div></div><label className="mt-5 block text-xs font-bold uppercase tracking-widest text-[var(--muted)]">Payment email</label><input value={email} onChange={e=>setEmail(e.target.value)} type="email" autoComplete="email" className="mt-2 w-full rounded-xl border border-[var(--border)] bg-[var(--background)] px-4 py-3 text-sm outline-none focus:border-[var(--primary)]"/><p className="mt-2 text-xs text-[var(--muted)]">Your signed-in email is prefilled. The current Paystack server flow uses the authenticated account email.</p></section>
       <section className="rounded-[28px] border border-[var(--border)] bg-[var(--surface)] p-6 shadow-sm sm:p-7"><div className="flex items-center gap-3"><CreditCard size={20}/><div><h2 className="font-bold">Payment method</h2><p className="mt-1 text-xs text-[var(--muted)]">Available methods are controlled by DRIGHT administrators.</p></div></div><div className="mt-5 space-y-3">{providers.length?providers.map(p=><button key={p.provider} onClick={()=>payWith(p.provider)} disabled={!rows.length||submitting} className={`flex w-full items-center justify-between rounded-2xl border p-4 text-left transition ${p.provider==="paystack"?"border-[var(--primary)] bg-[var(--background)] hover:shadow-md":"border-[var(--border)] opacity-70"} disabled:cursor-not-allowed disabled:opacity-50`}><span><span className="flex items-center gap-2 font-bold"><CreditCard size={17}/>{labels[p.provider]||p.provider}</span><span className="mt-1 block text-xs text-[var(--muted)]">{p.provider==="paystack"?"Secure hosted payment · current launch provider":"Registered provider · connector not live"}</span></span><span className="text-sm font-bold">{p.provider==="paystack"?"Continue":"Unavailable"}</span></button>):<p className="rounded-xl border border-dashed border-[var(--border)] p-4 text-center text-sm text-[var(--muted)]">No payment methods are currently available.</p>}</div></section>
       {error&&<div className="rounded-2xl border border-red-500/20 bg-red-500/5 p-4 text-sm text-red-700 dark:text-red-300">{error}</div>}
     </main>
     <aside className="h-fit space-y-4 lg:sticky lg:top-24"><section className="rounded-[28px] border border-[var(--border)] bg-[var(--surface)] p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-bold">Order summary</h2><ReceiptText size={18}/></div><div className="mt-5 space-y-3 text-sm"><div className="flex justify-between"><span className="text-[var(--muted)]">Subtotal</span><span>{currencies.length===1?currencies[0]:"—"} {subtotal.toLocaleString()}</span></div><div className="flex justify-between"><span className="text-[var(--muted)]">Discounts</span><span>—</span></div><div className="flex justify-between"><span className="text-[var(--muted)]">Taxes / fees</span><span>Finalized securely</span></div><div className="flex justify-between border-t border-[var(--border)] pt-4 text-xl font-bold"><span>Order total</span><span>{currencies.length===1?currencies[0]:"—"} {displayTotal.toLocaleString()}</span></div></div><p className="mt-4 text-xs leading-5 text-[var(--muted)]">The amount shown here is an estimate for display. The Paystack initializer recomputes item prices, platform fees, task fees and the authoritative total on the server before payment.</p><button onClick={()=>payWith("paystack")} disabled={!rows.length||submitting||currencies.length!==1} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-[var(--primary)] px-5 py-3.5 text-sm font-bold text-[var(--background)] disabled:cursor-not-allowed disabled:opacity-50">{submitting?"Preparing secure payment…":"Continue to secure payment"}<ChevronRight size={17}/></button></section><section className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><div className="flex gap-3"><ShieldCheck size={19} className="shrink-0"/><div><p className="text-sm font-bold">Protected payment flow</p><p className="mt-1 text-xs leading-5 text-[var(--muted)]">DRIGHT does not collect your Paystack card, PIN or bank credentials. Payment status is confirmed by the server-side provider flow.</p></div></div></section><section className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><div className="flex gap-3"><FileText size={18} className="shrink-0"/><div><p className="text-sm font-bold">After payment</p><p className="mt-1 text-xs leading-5 text-[var(--muted)]">You can open the order receipt, track payment status, access eligible digital products, and contact support using the order and product IDs.</p></div></div></section></aside>
   </div>
 </div>;
}
