"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, CreditCard, LockKeyhole, ShoppingBag } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Row={id:string;quantity:number;unit_price:number;currency:string|null;marketplace_item_id:string;item?:{id:string;public_id?:string;title:string;item_type:string|null;price?:number;currency_code?:string}};
type Provider={provider:string;enabled:boolean;mode:string};

const labels:Record<string,string>={paystack:"Paystack",flutterwave:"Flutterwave",wise:"Wise",stripe:"Stripe",coinbase_commerce:"Coinbase Commerce",nowpayments:"NOWPayments"};

export default function CheckoutPage(){
 const supabase=createClient();
 const [rows,setRows]=useState<Row[]>([]); const [cartId,setCartId]=useState(""); const [providers,setProviders]=useState<Provider[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [submitting,setSubmitting]=useState(false); const [paymentUrl,setPaymentUrl]=useState(""); const [orderId,setOrderId]=useState("");
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href="/login?next=/checkout";return} const cartResult=await supabase.from("carts").select("id").eq("user_id",user.id).maybeSingle(); if(cartResult.error||!cartResult.data){setError(cartResult.error?.message||"Your cart is empty.");setLoading(false);return} setCartId(cartResult.data.id); const r=await supabase.from("cart_items").select("id,quantity,unit_price,currency,marketplace_item_id,marketplace_items(id,public_id,title,item_type,price,currency_code)").eq("cart_id",cartResult.data.id); if(r.error)setError(r.error.message);else setRows((r.data||[]).map((x:any)=>({...x,item:x.marketplace_items}))); const p=await supabase.from("payment_provider_configs").select("provider,enabled,mode").eq("enabled",true); if(!p.error)setProviders(p.data||[]); setLoading(false)})()},[supabase]);
 const currencies=[...new Set(rows.map(r=>r.currency||r.item?.currency_code||"USD"))]; const subtotal=rows.reduce((s,r)=>s+(Number(r.item?.price??r.unit_price)||0)*r.quantity,0);
 async function payWith(provider:string){if(provider!=="paystack"){setError(`${labels[provider]||provider} is enabled in the platform registry but its checkout connector is not live yet.`);return} setSubmitting(true);setError(""); const {data:{session}}=await supabase.auth.getSession(); if(!session){setError("Please sign in again.");setSubmitting(false);return} if(!cartId||!rows.length){setError("Your cart is empty.");setSubmitting(false);return} if(currencies.length!==1){setError("Your cart contains multiple currencies. Please purchase these items separately.");setSubmitting(false);return} const result=await supabase.functions.invoke("paystack-initialize",{body:{cart_id:cartId}}); if(result.error){setError(result.error.message||"Unable to start payment.");setSubmitting(false);return} if(result.data?.authorization_url){setOrderId(result.data.public_order_id||result.data.order_id||"");setPaymentUrl(result.data.authorization_url);window.location.href=result.data.authorization_url;return} setError(result.data?.error||"Unable to start payment.");setSubmitting(false);}
 if(loading)return <div className="mx-auto max-w-5xl px-4 py-8"><div className="h-80 animate-pulse rounded-[2rem] border border-[var(--border)] bg-[var(--surface)]"/></div>;
 if(paymentUrl)return <div className="mx-auto max-w-3xl px-4 py-12 text-center"><LockKeyhole size={28} className="mx-auto"/><h1 className="mt-5 text-3xl font-semibold">Redirecting to secure payment</h1><p className="mt-3 text-sm text-[var(--muted)]">Order {orderId||"created"}. You will complete payment on Paystack's secure checkout.</p><a href={paymentUrl} className="mt-6 inline-flex rounded-xl bg-[var(--primary)] px-5 py-3 text-sm font-semibold text-[var(--background)]">Continue to Paystack</a></div>;
 return <div className="mx-auto max-w-5xl px-4 py-7 sm:px-6 lg:px-8"><Link href="/cart" className="inline-flex items-center gap-2 text-sm font-medium text-[var(--muted)]"><ArrowLeft size={16}/> Back to cart</Link><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_340px]"><section className="rounded-[2rem] border border-[var(--border)] bg-[var(--surface)] p-6 sm:p-8"><div className="flex items-center gap-3"><ShoppingBag size={21}/><div><p className="text-xs font-semibold uppercase tracking-widest text-[var(--muted)]">Checkout</p><h1 className="text-2xl font-semibold">Review your order</h1></div></div><div className="mt-7 space-y-3">{rows.length?rows.map(r=><div key={r.id} className="flex items-center justify-between gap-4 rounded-2xl border border-[var(--border)] p-4"><div className="min-w-0"><p className="truncate font-medium">{r.item?.title||"Listing"}</p><p className="mt-1 text-xs text-[var(--muted)]">{r.item?.item_type||"listing"} · Qty {r.quantity} · ID {r.item?.public_id||r.marketplace_item_id}</p></div><p className="shrink-0 text-sm font-semibold">{r.currency||r.item?.currency_code||"USD"} {(Number(r.item?.price??r.unit_price)*r.quantity).toLocaleString()}</p></div>):<div className="rounded-2xl border border-dashed border-[var(--border)] p-10 text-center text-sm text-[var(--muted)]">Your cart is empty. <Link className="font-semibold underline" href="/marketplace">Browse marketplace</Link></div>}</div>{error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}</section><aside className="h-fit rounded-[2rem] border border-[var(--border)] bg-[var(--surface)] p-6 lg:sticky lg:top-24"><h2 className="font-semibold">Order summary</h2><div className="mt-5 flex justify-between text-sm"><span className="text-[var(--muted)]">Subtotal</span><span>{currencies.length===1?currencies[0]:"—"} {subtotal.toLocaleString()}</span></div><div className="mt-4 flex justify-between border-t border-[var(--border)] pt-4 text-lg font-semibold"><span>Total</span><span>{currencies.length===1?currencies[0]:"—"} {subtotal.toLocaleString()}</span></div><div className="mt-6 space-y-2">{providers.length?providers.map(p=><button key={p.provider} onClick={()=>payWith(p.provider)} disabled={!rows.length||submitting} className="flex w-full items-center justify-between rounded-xl border border-[var(--border)] px-4 py-3.5 text-sm font-semibold transition hover:shadow-md disabled:opacity-50"><span className="flex items-center gap-2"><CreditCard size={17}/>{labels[p.provider]||p.provider}</span><span>Pay</span></button>):<p className="rounded-xl border border-dashed border-[var(--border)] p-4 text-center text-sm text-[var(--muted)]">No payment methods are currently available.</p>}</div><p className="mt-4 text-center text-xs leading-5 text-[var(--muted)]">Payment methods are controlled by DRIGHT administrators. Payment credentials are never collected by this page.</p></aside></div></div>;
}
