"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Search, Sparkles, Users } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Creator={user_id:string;public_id:string|null;display_name:string|null;headline:string|null;bio:string|null;specialties:string[]};

export default function CreatorsPage(){
 const supabase=useMemo(()=>createClient(),[]);const [items,setItems]=useState<Creator[]>([]);const [query,setQuery]=useState("");const [loading,setLoading]=useState(true);
 useEffect(()=>{let cancelled=false;(async()=>{setLoading(true);let q=supabase.from('creator_profiles').select('user_id,public_id,display_name,headline,bio,specialties').eq('status','active').limit(48);if(query.trim())q=q.or(`display_name.ilike.%${query.trim()}%,headline.ilike.%${query.trim()}%,bio.ilike.%${query.trim()}%`);const {data}=await q;if(!cancelled){setItems((data||[]) as Creator[]);setLoading(false);}})();return()=>{cancelled=true};},[query,supabase]);
 return <main className="mx-auto max-w-7xl px-4 py-7 sm:px-6"><section className="rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-6 sm:p-8"><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[var(--background)]"><Sparkles/></div><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--muted)]">DRIGHT Social</p><h1 className="text-3xl font-bold">Discover creators</h1></div></div><p className="mt-3 max-w-3xl text-sm leading-6 text-[var(--muted)]">Find creators, contributors and campaign-ready talent without creating a separate social graph.</p><label className="relative mt-5 block"><Search size={16} className="absolute left-3 top-3.5 text-[var(--muted)]"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search creators…" className="w-full rounded-xl border border-[var(--border)] bg-[var(--background)] py-3 pl-9 pr-4 text-sm outline-none focus:ring-2 focus:ring-[var(--accent)]"/></label></section><section className="mt-6">{loading?<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{Array.from({length:6}).map((_,i)=><div key={i} className="h-48 animate-pulse rounded-2xl bg-[var(--surface)]"/>)}</div>:items.length===0?<div className="rounded-2xl border border-dashed border-[var(--border)] p-12 text-center"><Users className="mx-auto text-[var(--muted)]"/><h2 className="mt-4 font-semibold">No public creator profiles yet</h2><p className="mt-2 text-sm text-[var(--muted)]">Creator profiles become discoverable when their public profile is activated.</p></div>:<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map(c=><article key={c.user_id} className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><div className="grid h-12 w-12 place-items-center rounded-full bg-[var(--background)] font-bold">{(c.display_name||'D').slice(0,1).toUpperCase()}</div><h2 className="mt-4 font-semibold">{c.display_name||'DRIGHT creator'}</h2><p className="mt-1 text-sm text-[var(--muted)]">{c.headline||'Creator and contributor'}</p><p className="mt-3 line-clamp-3 text-sm leading-5 text-[var(--muted)]">{c.bio||'Public creator profile.'}</p><div className="mt-4 flex flex-wrap gap-2">{(c.specialties||[]).slice(0,4).map(s=><span key={s} className="rounded-full bg-[var(--background)] px-2 py-1 text-[10px] text-[var(--muted)]">{s}</span>)}</div><Link href={`/profile/${c.user_id}`} className="mt-5 inline-flex rounded-xl border border-[var(--border)] px-4 py-2 text-xs font-semibold">View profile</Link></article>)}</div>}</section></main>;
}
