"use client";

import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { ChevronLeft, ChevronRight, DollarSign, FileText, LayoutDashboard, ListChecks, LogOut, Menu, Megaphone, Search, Settings, ShieldCheck, Users, X, FileEdit, Gavel, UserCog, Palette, ClipboardList, Headphones } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type NavItem = readonly [string, string, any, string];
const nav: NavItem[] = [
  ["Overview", "/admin", LayoutDashboard, "admin.dashboard.view"], ["CRM & Customer Success", "/admin/crm", Users, "crm.customers.view"], ["Listings & Reviews", "/admin/listings", ListChecks, "listings.review"], ["Moderation", "/admin/moderation", Gavel, "moderation.manage"], ["CMS", "/admin/cms", FileEdit, "cms.view"], ["Administrators", "/admin/administrators", UserCog, "admins.manage"], ["Roles & Permissions", "/admin/roles", ShieldCheck, "roles.manage"], ["Themes", "/admin/themes", Palette, "themes.manage"], ["Audit Log", "/admin/audit", ClipboardList, "audit.view"], ["Promotions & Advertising", "/admin/promotions", Megaphone, "promotions.manage"], ["Feature Control", "/admin/features", Settings, "features.manage"], ["ID Lookup", "/admin/ids", Search, "admin.dashboard.view"], ["Finance", "/admin/finance", DollarSign, "finance.manage"], ["Refunds & Disputes", "/admin/refunds", FileText, "refunds.manage"],
];
function AdminNavItem({ item, collapsed, onNavigate }: { item: NavItem; collapsed: boolean; onNavigate?: () => void }) { const pathname=usePathname(); const [label,href,Icon]=item; const active=href==="/admin"?pathname===href:pathname.startsWith(href); return <Link href={href} onClick={onNavigate} title={collapsed?label:undefined} aria-current={active?"page":undefined} className={`flex min-h-10 items-center gap-3 rounded-[var(--radius-md)] px-3 py-2.5 text-sm font-medium transition-all ${active?"bg-[var(--accent-soft)] text-[var(--accent)] shadow-[var(--shadow-xs)]":"text-[var(--muted)] hover:bg-[var(--surface-muted)] hover:text-[var(--foreground)]"} ${collapsed?"justify-center":""}`}><Icon size={18} strokeWidth={active?2.25:1.9}/><span className={collapsed?"sr-only":""}>{label}</span>{!collapsed&&active&&<span className="ml-auto h-1.5 w-1.5 rounded-full bg-[var(--accent)]"/>}</Link>; }

export function AdminShell({ children }: { children: React.ReactNode }) {
  const [collapsed,setCollapsed]=useState(false); const [mobileOpen,setMobileOpen]=useState(false); const [checking,setChecking]=useState(true); const [visibleNav,setVisibleNav]=useState<NavItem[]>([]); const router=useRouter(); const supabase=createClient();
  useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser(); if(!user){router.replace("/login?next=/admin");return;} const {data:canView}=await supabase.rpc("admin_has_permission",{p_permission:"admin.dashboard.view",p_user_id:user.id}); if(!canView){router.replace("/dashboard");return;} const checks=await Promise.all(nav.map(async item=>{const {data}=await supabase.rpc("admin_has_permission",{p_permission:item[3],p_user_id:user.id});return [item,!!data] as const;})); setVisibleNav(checks.filter(([,allowed])=>allowed).map(([item])=>item)); setChecking(false);})()},[router,supabase]);
  async function signOut(){await supabase.auth.signOut();router.replace("/");}
  if(checking)return <div className="flex min-h-screen items-center justify-center bg-[var(--background)] text-sm text-[var(--muted)]"><div className="flex items-center gap-3"><span className="h-2 w-2 animate-pulse rounded-full bg-[var(--accent)]"/>Checking administrator access…</div></div>;
  const sidebar=<aside className={`${collapsed?"w-[78px]":"w-[272px]"} hidden shrink-0 border-r border-[var(--border)] bg-[var(--surface)]/95 px-3 py-4 backdrop-blur transition-[width] duration-200 lg:flex lg:flex-col`}><div className={`flex h-12 items-center ${collapsed?"justify-center":"justify-between"} px-2`}><Link href="/admin" className="flex items-center gap-2 text-xl font-black tracking-[-0.04em]"><span className="grid h-8 w-8 place-items-center rounded-[10px] bg-[var(--accent)] text-xs text-[var(--primary-contrast)]">D</span>{!collapsed&&<span>DRIGHT Admin</span>}</Link>{!collapsed&&<button onClick={()=>setCollapsed(true)} aria-label="Collapse admin navigation" className="rounded-[var(--radius-md)] p-2 text-[var(--muted)] hover:bg-[var(--surface-muted)]"><ChevronLeft size={18}/></button>}</div>{collapsed&&<button onClick={()=>setCollapsed(false)} aria-label="Expand admin navigation" className="mb-2 mt-2 rounded-[var(--radius-md)] p-2 text-[var(--muted)] hover:bg-[var(--surface-muted)]"><ChevronRight size={18} className="mx-auto"/></button>}<div className="mx-1 mt-3 rounded-[var(--radius-lg)] border border-[var(--border)] bg-[var(--surface-muted)] p-3"><div className="flex items-center gap-2"><ShieldCheck size={17} className="text-[var(--accent)]"/>{!collapsed&&<div><p className="text-xs font-bold">Administrator</p><p className="text-[10px] text-[var(--muted)]">Permission-aware control space</p></div>}</div></div><nav className="mt-2 flex-1 space-y-1 overflow-y-auto pb-2">{!collapsed&&<div className="mb-2 mt-3 px-3 text-[10px] font-bold uppercase tracking-[0.16em] text-[var(--muted)]">Control Center</div>}{visibleNav.map(item=><AdminNavItem key={item[1]} item={item} collapsed={collapsed}/>)}</nav><div className="space-y-1 border-t border-[var(--border)] pt-3"><Link href="/dashboard" title={collapsed?"Return to DRIGHT":undefined} className={`flex min-h-10 items-center gap-3 rounded-[var(--radius-md)] px-3 py-2.5 text-sm font-medium text-[var(--muted)] hover:bg-[var(--surface-muted)] hover:text-[var(--foreground)] ${collapsed?"justify-center":""}`}><Users size={18}/><span className={collapsed?"sr-only":""}>Return to DRIGHT</span></Link><Link href="/support" title={collapsed?"Support":undefined} className={`flex min-h-10 items-center gap-3 rounded-[var(--radius-md)] px-3 py-2.5 text-sm font-medium text-[var(--muted)] hover:bg-[var(--surface-muted)] hover:text-[var(--foreground)] ${collapsed?"justify-center":""}`}><Headphones size={18}/><span className={collapsed?"sr-only":""}>Support</span></Link><button onClick={signOut} title={collapsed?"Logout":undefined} className={`flex min-h-10 w-full items-center gap-3 rounded-[var(--radius-md)] px-3 py-2.5 text-sm font-medium text-[var(--muted)] hover:bg-[var(--surface-muted)] hover:text-[var(--foreground)] ${collapsed?"justify-center":""}`}><LogOut size={18}/><span className={collapsed?"sr-only":""}>Logout</span></button></div></aside>;
  const mobile=<div className="lg:hidden">{mobileOpen&&<div className="fixed inset-0 z-50 bg-slate-950/45 backdrop-blur-[2px]" onClick={()=>setMobileOpen(false)}><aside onClick={e=>e.stopPropagation()} className="flex h-full w-[min(88vw,330px)] flex-col overflow-hidden border-r border-[var(--border)] bg-[var(--surface)] p-3 shadow-[var(--shadow-xl)]"><div className="flex h-12 items-center justify-between px-2"><Link href="/admin" onClick={()=>setMobileOpen(false)} className="text-lg font-black">DRIGHT Admin</Link><button onClick={()=>setMobileOpen(false)} aria-label="Close admin navigation" className="rounded-[var(--radius-md)] p-2 text-[var(--muted)] hover:bg-[var(--surface-muted)]"><X/></button></div><nav className="mt-3 flex-1 space-y-1 overflow-y-auto">{visibleNav.map(item=><AdminNavItem key={item[1]} item={item} collapsed={false} onNavigate={()=>setMobileOpen(false)}/>)}</nav><div className="border-t border-[var(--border)] pt-3"><Link href="/dashboard" onClick={()=>setMobileOpen(false)} className="flex min-h-10 items-center gap-3 rounded-[var(--radius-md)] px-3 py-2.5 text-sm text-[var(--muted)]"><Users size={18}/>Return to DRIGHT</Link><Link href="/support" onClick={()=>setMobileOpen(false)} className="flex min-h-10 items-center gap-3 rounded-[var(--radius-md)] px-3 py-2.5 text-sm text-[var(--muted)]"><Headphones size={18}/>Support</Link></div></aside></div>}</div>;
  return <div className="flex min-h-screen bg-[var(--background)] text-[var(--foreground)]">{mobile}{sidebar}<div className="min-w-0 flex-1"><header className="sticky top-0 z-30 flex min-h-16 items-center gap-2 border-b border-[var(--border)] bg-[var(--background)]/88 px-3 backdrop-blur-xl sm:px-5"><button className="rounded-[var(--radius-md)] p-2.5 hover:bg-[var(--surface)] lg:hidden" onClick={()=>setMobileOpen(true)} aria-label="Open admin menu"><Menu size={20}/></button><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">DRIGHT Admin Panel</p><p className="hidden text-xs text-[var(--muted)] sm:block">Secure operational control center</p></div><Link href="/dashboard" className="hidden rounded-[var(--radius-md)] border border-[var(--border)] px-3 py-2 text-sm font-medium text-[var(--muted)] transition hover:bg-[var(--surface)] hover:text-[var(--foreground)] sm:block">User Space</Link></header><main>{children}</main></div></div>;
}
