"use client";

import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { Bell, ChevronLeft, ChevronRight, CircleDollarSign, Compass, Gift, HelpCircle, Home, Languages, LogOut, Menu, MessageSquare, Search, Settings, ShieldCheck, ShoppingBag, Sparkles, Store, UserRound, Users, Wallet, X, Rss, Trophy, Megaphone } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { getFeatureMap, featureUsable, type Feature } from "@/lib/features";
import { AdminShell } from "@/components/admin-shell";
import { ThemeSwitcher } from "@/components/theme-switcher";

const primary = [["Dashboard","/dashboard",Home,null],["Marketplace","/marketplace",Compass,null],["Social Feed","/social",Rss,"social_feed"],["Communities","/communities",Users,"communities_social"],["Leaderboards","/leaderboards",Trophy,"social_leaderboards"],["Notifications","/notifications",Bell,"announcements"]] as const;
const account = [["Profile","/profile",UserRound,null],["Referral","/referrals",Users,"referrals"],["Wallet","/wallet",Wallet,"wallet"],["Reward Center","/rewards",Gift,null],["Orders","/orders",ShoppingBag,"orders"],["Messages","/messages",MessageSquare,"messages"]] as const;
const growth = [["Affiliate Center","/affiliate/commissions",CircleDollarSign,"affiliate_center"],["Vendor Center","/vendor",Store,"vendor_center"],["DRIGHT Gen.ai","/gen-ai",Sparkles,null]] as const;
type NavItemType = readonly [string,string,any,string|null];

function NavItem({ item, collapsed, onNavigate }: { item: NavItemType; collapsed: boolean; onNavigate?: () => void }) {
  const pathname = usePathname(); const [label, href, Icon] = item; const active = pathname === href || (href !== "/dashboard" && pathname.startsWith(`${href}/`));
  return <Link href={href} onClick={onNavigate} title={collapsed ? label : undefined} aria-current={active ? "page" : undefined} className={`group flex min-h-10 items-center gap-3 rounded-[var(--radius-md)] px-3 py-2.5 text-sm font-medium transition-all duration-200 ${active ? "bg-[var(--accent-soft)] text-[var(--accent)] shadow-[var(--shadow-xs)]" : "text-[var(--muted)] hover:bg-[var(--surface-muted)] hover:text-[var(--foreground)]"} ${collapsed ? "justify-center" : ""}`}><Icon size={18} strokeWidth={active ? 2.25 : 1.9}/><span className={collapsed ? "sr-only" : ""}>{label}</span>{!collapsed && active && <span className="ml-auto h-1.5 w-1.5 rounded-full bg-[var(--accent)]"/>}</Link>;
}
function SectionLabel({ children, collapsed }: { children: React.ReactNode; collapsed: boolean }) { return <div className={`mb-2 mt-5 px-3 text-[10px] font-bold uppercase tracking-[0.16em] text-[var(--muted)] ${collapsed ? "sr-only" : ""}`}>{children}</div>; }

export function AppShell({ children }: { children: React.ReactNode }) {
  const pathname = usePathname(); const [collapsed, setCollapsed] = useState(false); const [mobileOpen, setMobileOpen] = useState(false); const [isAdmin, setIsAdmin] = useState(false); const [features, setFeatures] = useState<Record<string, Feature>>({}); const [profile, setProfile] = useState<{ full_name: string | null; username: string | null }>({ full_name: null, username: null }); const router = useRouter(); const supabase = useMemo(() => createClient(), []);
  useEffect(() => { let cancelled=false; (async()=>{ const {data:{user}}=await supabase.auth.getUser(); if(!user||cancelled)return; const [{data:isSuper},featureMap,profileResult]=await Promise.all([supabase.rpc("is_super_admin",{check_user_id:user.id}),getFeatureMap().catch(()=>({})),supabase.from("profiles").select("full_name,username").eq("id",user.id).maybeSingle()]); if(cancelled)return; setIsAdmin(Boolean(isSuper)); setFeatures(featureMap); setProfile(profileResult.data ?? {full_name:null,username:null}); })(); return()=>{cancelled=true}; },[supabase]);
  if (pathname === "/admin" || pathname.startsWith("/admin/")) return <AdminShell>{children}</AdminShell>;
  async function signOut(){await supabase.auth.signOut();router.replace("/");}
  const enabled=(key:string|null)=>!key||featureUsable(features[key]); const filterItems=(items:readonly NavItemType[])=>items.filter(item=>enabled(item[3])); const p=filterItems(primary),a=filterItems(account),g=filterItems(growth); const all=[...p,...a,...g] as NavItemType[]; const name=profile.full_name||profile.username||"there";
  const adminItem:NavItemType=["Admin Panel","/admin",ShieldCheck,null]; const campaignItem:NavItemType=["Campaigns","/admin/promotions",Megaphone,"promotions"];
  const sidebar=<aside className={`${collapsed?"w-[78px]":"w-[272px]"} hidden shrink-0 border-r border-[var(--border)] bg-[var(--surface)]/95 px-3 py-4 backdrop-blur transition-[width] duration-200 lg:flex lg:flex-col`}><div className={`flex h-12 items-center ${collapsed?"justify-center":"justify-between"} px-2`}><Link href="/dashboard" className="flex items-center gap-2 text-xl font-black tracking-[-0.04em]"><span className="grid h-8 w-8 place-items-center rounded-[10px] bg-[var(--primary)] text-xs text-[var(--primary-contrast)]">D</span>{!collapsed&&<span>DRIGHT</span>}</Link>{!collapsed&&<button onClick={()=>setCollapsed(true)} aria-label="Collapse navigation" className="rounded-[var(--radius-md)] p-2 text-[var(--muted)] transition hover:bg-[var(--surface-muted)] hover:text-[var(--foreground)]"><ChevronLeft size={18}/></button>}</div>{collapsed&&<button onClick={()=>setCollapsed(false)} aria-label="Expand navigation" className="mb-2 mt-2 rounded-[var(--radius-md)] p-2 text-[var(--muted)] transition hover:bg-[var(--surface-muted)] hover:text-[var(--foreground)]"><ChevronRight size={18} className="mx-auto"/></button>}{!collapsed&&<div className="mx-1 mt-3 rounded-[var(--radius-lg)] border border-[var(--border)] bg-[var(--surface-muted)] p-3"><p className="truncate text-xs font-semibold">{name}</p><p className="mt-0.5 text-[10px] text-[var(--muted)]">Your DRIGHT command center</p></div>}<nav className="mt-2 flex-1 overflow-y-auto pb-2 pr-1"><SectionLabel collapsed={collapsed}>Discover</SectionLabel>{p.map(item=><NavItem key={item[1]} item={item} collapsed={collapsed}/>)}<SectionLabel collapsed={collapsed}>Your DRIGHT</SectionLabel>{a.map(item=><NavItem key={item[1]} item={item} collapsed={collapsed}/>)}<SectionLabel collapsed={collapsed}>Build & Earn</SectionLabel>{g.map(item=><NavItem key={item[1]} item={item} collapsed={collapsed}/>)}{isAdmin&&<><SectionLabel collapsed={collapsed}>Workspace</SectionLabel><NavItem item={campaignItem} collapsed={collapsed}/><SectionLabel collapsed={collapsed}>Administration</SectionLabel><NavItem item={adminItem} collapsed={collapsed}/></>}</nav><div className="space-y-1 border-t border-[var(--border)] pt-3"><NavItem item={["Settings","/settings",Settings,null]} collapsed={collapsed}/>{enabled("help")&&<NavItem item={["Help","/help",HelpCircle,"help"]} collapsed={collapsed}/>}<button onClick={signOut} title={collapsed?"Logout":undefined} className={`flex min-h-10 w-full items-center gap-3 rounded-[var(--radius-md)] px-3 py-2.5 text-sm font-medium text-[var(--muted)] transition hover:bg-[var(--surface-muted)] hover:text-[var(--foreground)] ${collapsed?"justify-center":""}`}><LogOut size={18}/><span className={collapsed?"sr-only":""}>Logout</span></button></div></aside>;
  const mobile=<div className="lg:hidden">{mobileOpen&&<div className="fixed inset-0 z-50 bg-slate-950/45 backdrop-blur-[2px]" onClick={()=>setMobileOpen(false)}><aside onClick={e=>e.stopPropagation()} className="flex h-full w-[min(88vw,330px)] flex-col overflow-hidden border-r border-[var(--border)] bg-[var(--surface)] p-3 shadow-[var(--shadow-xl)]"><div className="flex h-12 items-center justify-between px-2"><Link href="/dashboard" onClick={()=>setMobileOpen(false)} className="flex items-center gap-2 text-xl font-black tracking-[-0.04em]"><span className="grid h-8 w-8 place-items-center rounded-[10px] bg-[var(--primary)] text-xs text-[var(--primary-contrast)]">D</span>DRIGHT</Link><button onClick={()=>setMobileOpen(false)} aria-label="Close navigation" className="rounded-[var(--radius-md)] p-2 text-[var(--muted)] hover:bg-[var(--surface-muted)]"><X/></button></div><div className="mx-1 mt-2 rounded-[var(--radius-lg)] border border-[var(--border)] bg-[var(--surface-muted)] p-3"><p className="truncate text-xs font-semibold">{name}</p><p className="mt-0.5 text-[10px] text-[var(--muted)]">Command center</p></div><nav className="mt-2 flex-1 overflow-y-auto">{all.map(item=><NavItem key={item[1]} item={item} collapsed={false} onNavigate={()=>setMobileOpen(false)}/>)}{isAdmin&&<><div className="my-3 border-t border-[var(--border)]"/><NavItem item={campaignItem} collapsed={false} onNavigate={()=>setMobileOpen(false)}/><NavItem item={adminItem} collapsed={false} onNavigate={()=>setMobileOpen(false)}/></>}<div className="my-3 border-t border-[var(--border)]"/><NavItem item={["Settings","/settings",Settings,null]} collapsed={false} onNavigate={()=>setMobileOpen(false)}/>{enabled("help")&&<NavItem item={["Help","/help",HelpCircle,"help"]} collapsed={false} onNavigate={()=>setMobileOpen(false)}/>}<button onClick={signOut} className="mt-1 flex min-h-10 w-full items-center gap-3 rounded-[var(--radius-md)] px-3 py-2.5 text-sm font-medium text-[var(--muted)]"><LogOut size={18}/>Logout</button></nav></aside></div>}</div>;
  return <div className="flex min-h-screen bg-[var(--background)] text-[var(--foreground)]">{mobile}{sidebar}<div className="min-w-0 flex-1"><header className="sticky top-0 z-30 flex min-h-16 items-center gap-2 border-b border-[var(--border)] bg-[var(--background)]/88 px-3 backdrop-blur-xl sm:px-5"><button className="rounded-[var(--radius-md)] p-2.5 hover:bg-[var(--surface)] lg:hidden" onClick={()=>setMobileOpen(true)} aria-label="Open menu"><Menu size={20}/></button><Link href="/dashboard" className="hidden text-sm font-bold tracking-tight sm:block lg:hidden">DRIGHT</Link><div className="min-w-0 flex-1"><Link href="/marketplace" className="flex h-10 max-w-3xl items-center gap-2 rounded-[var(--radius-md)] border border-[var(--border)] bg-[var(--surface)] px-3 text-sm text-[var(--muted)] shadow-[var(--shadow-xs)] transition hover:border-[var(--border-strong)] hover:text-[var(--foreground)]"><Search size={17}/><span className="truncate">Search products, services, courses, jobs and social content...</span></Link></div><div className="hidden items-center gap-1 sm:flex"><Link href="/dashboard" className={`rounded-[var(--radius-md)] px-3 py-2 text-sm font-medium ${pathname==="/dashboard"?"bg-[var(--surface)] text-[var(--foreground)]":"text-[var(--muted)] hover:bg-[var(--surface)]"}`}>Dashboard</Link><Link href="/notifications" className="rounded-[var(--radius-md)] p-2.5 text-[var(--muted)] hover:bg-[var(--surface)]" aria-label="Notifications"><Bell size={19}/></Link><button className="rounded-[var(--radius-md)] p-2.5 text-[var(--muted)] hover:bg-[var(--surface)]" title="Language" aria-label="Language"><Languages size={19}/></button><ThemeSwitcher/></div><div className="sm:hidden"><ThemeSwitcher/></div></header><main>{children}</main></div></div>;
}
