"use client";

import Link from "next/link";
import { ArrowRight, BarChart3, DollarSign, FileText, Gavel, Megaphone, Settings2, ShieldCheck, ShoppingCart, Users, FileEdit, UserCog } from "lucide-react";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

const cards = [
  { title: "Administrators", description: "Review activation requests, supervision and administrative access.", href: "/admin/administrators", icon: UserCog, permission: "admins.manage" },
  { title: "Roles & Permissions", description: "Control least-privilege administrator role bundles.", href: "/admin/roles", icon: ShieldCheck, permission: "roles.manage" },
  { title: "CMS", description: "Manage versioned pages, reusable content blocks and publishing.", href: "/admin/cms", icon: FileEdit, permission: "cms.view" },
  { title: "Moderation", description: "Review reports, resolve cases and record trust decisions.", href: "/admin/moderation", icon: Gavel, permission: "moderation.manage" },
  { title: "Themes", description: "Manage centralized DRIGHT theme availability.", href: "/admin/themes", icon: Settings2, permission: "themes.manage" },
  { title: "Audit Log", description: "Inspect sensitive governance and operational events.", href: "/admin/audit", icon: FileText, permission: "audit.view" },
  { title: "Feature Control", description: "Manage platform feature visibility and rollout states.", href: "/admin/features", icon: ShieldCheck, permission: "features.manage" },
  { title: "Finance", description: "Review financial operations, ledger activity and controls.", href: "/admin/finance", icon: DollarSign, permission: "finance.manage" },
  { title: "Refunds & Disputes", description: "Review customer cases, decisions and audit history.", href: "/admin/refunds", icon: FileText, permission: "refunds.manage" },
  { title: "Promotions & Advertising", description: "Review sponsored campaigns, pricing configuration and performance.", href: "/admin/promotions", icon: Megaphone, permission: "promotions.manage" },
];

export default function AdminHomePage() {
  const [name,setName]=useState("Administrator"); const [visible,setVisible]=useState<typeof cards>([]); const [stats,setStats]=useState({users:0,listings:0,orders:0,reports:0}); const supabase=createClient();
  useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data}=await supabase.from("profiles").select("username,full_name").eq("id",user.id).maybeSingle();setName(data?.full_name||data?.username||"Administrator");const checks=await Promise.all(cards.map(async c=>{const {data:ok}=await supabase.rpc("admin_has_permission",{p_permission:c.permission,p_user_id:user.id});return [c,!!ok] as const;}));setVisible(checks.filter(([,ok])=>ok).map(([c])=>c));const [u,l,o,r]=await Promise.all([supabase.from("profiles").select("id",{count:"exact",head:true}),supabase.from("listing_submissions").select("id",{count:"exact",head:true}),supabase.from("orders").select("id",{count:"exact",head:true}),supabase.from("reports").select("id",{count:"exact",head:true}).neq("status","resolved")]);setStats({users:u.count||0,listings:l.count||0,orders:o.count||0,reports:r.count||0});})();},[supabase]);
  return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div className="rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-6 sm:p-8"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-widest text-[var(--muted)]">DRIGHT Administration</p><h1 className="mt-2 text-3xl font-semibold">Enterprise Control Center</h1><p className="mt-2 max-w-2xl text-sm text-[var(--muted)]">Welcome, {name}. Governance, commerce, trust, content and platform operations are connected to the existing DRIGHT architecture.</p></div><ShieldCheck className="hidden sm:block" size={38}/></div></div><section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Users",stats.users,Users],["Listing submissions",stats.listings,ShoppingCart],["Orders",stats.orders,BarChart3],["Open reports",stats.reports,Gavel]].map(([label,value,Icon]:any)=><div key={label as string} className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><Icon size={19}/><p className="mt-4 text-xs uppercase tracking-widest text-[var(--muted)]">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>)}</section><section className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{visible.map(({title,description,href,icon:Icon})=><Link key={href} href={href} className="group rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5 transition hover:-translate-y-0.5 hover:bg-[var(--background)]"><div className="flex items-center justify-between"><Icon size={21}/><ArrowRight size={17} className="text-[var(--muted)] transition group-hover:translate-x-1"/></div><h2 className="mt-6 font-semibold">{title}</h2><p className="mt-2 text-sm text-[var(--muted)]">{description}</p></Link>)}</section></main>;
}
