"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { ArrowLeft, CheckCircle2, Clock3, Copy, ExternalLink, MessageCircle, Share2, ShoppingBag, Sparkles } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Item = { id:string; title:string; description:string|null; item_type:string|null; price:number|null; currency_code:string|null; status:string|null; created_at:string|null };

export default function ListingDetailPage() {
 const params=useParams<{id:string}>(); const id=typeof params.id==="string"?params.id:""; const supabase=createClient();
 const [item,setItem]=useState<Item|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [copied,setCopied]=useState(false); const [adding,setAdding]=useState(false); const [added,setAdded]=useState(false);
 useEffect(()=>{ if(!id)return; (async()=>{setLoading(true);setError(""); const {data,error:e}=await supabase.from("marketplace_items").select("id,title,description,item_type,price,currency_code,status,created_at").eq("id",id).eq("status","published").maybeSingle(); if(e)setError(e.message); else setItem(data as Item|null); setLoading(false);})(); },[id]);
 async function copyId(){try{await navigator.clipboard?.writeText(id)}catch{}setCopied(true);window.setTimeout(()=>setCopied(false),1600)}
 async function shareListing(){const d={title:item?.title||"DRIGHT listing",text:"View this DRIGHT listing",url:window.location.href};if(navigator.share)await navigator.share(d).catch(()=>undefined);else await copyId()}
 async function addToCart(){
  setAdding(true);setError("");
  const {data:{user}}=await supabase.auth.getUser(); if(!user){window.location.href=`/login?next=${encodeURIComponent(`/marketplace/${id}`)}`;return;}
  let {data:cart,error:ce}=await supabase.from("carts").select("id").eq("user_id",user.id).maybeSingle();
  if(ce){setError(ce.message);setAdding(false);return}
  if(!cart){const created=await supabase.from("carts").insert({user_id:user.id}).select("id").single();if(created.error){setError(created.error.message);setAdding(false);return}cart=created.data}
  const existing=await supabase.from("cart_items").select("id,quantity").eq("cart_id",cart.id).eq("marketplace_item_id",id).maybeSingle();
  if(existing.error){setError(existing.error.message);setAdding(false);return}
  const price=item?.price??0,currency_code=item?.currency_code||"USD";
  const result=existing.data?await supabase.from("cart_items").update({quantity:existing.data.quantity+1,unit_price:price,currency_code}).eq("id",existing.data.id):await supabase.from("cart_items").insert({cart_id:cart.id,marketplace_item_id:id,quantity:1,unit_price:price,currency_code});
  if(result.error)setError(result.error.message);else setAdded(true);setAdding(false);
 }
 if(loading)return <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6"><div className="grid gap-6 lg:grid-cols-[minmax(0,1.35fr)_380px]"><div className="h-[520px] animate-pulse rounded-[2rem] border border-[var(--border)] bg-[var(--surface)]"/><div className="h-[430px] animate-pulse rounded-[2rem] border border-[var(--border)] bg-[var(--surface)]"/></div></div>;
 if(error&&!item)return <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6"><Link href="/marketplace" className="inline-flex items-center gap-2 text-sm text-[var(--muted)]"><ArrowLeft size={16}/> Back</Link><div className="mt-6 rounded-2xl border border-red-200 bg-red-50 p-6 text-sm text-red-700">Could not load this listing: {error}</div></div>;
 if(!item)return <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6"><Link href="/marketplace" className="inline-flex items-center gap-2 text-sm text-[var(--muted)]"><ArrowLeft size={16}/> Back</Link><div className="mt-6 rounded-[2rem] border border-dashed border-[var(--border)] bg-[var(--surface)] p-12 text-center"><ShoppingBag className="mx-auto" size={28}/><h1 className="mt-4 text-xl font-semibold">Listing not found</h1><p className="mt-2 text-sm text-[var(--muted)]">This listing may be unpublished or no longer available.</p><Link href="/marketplace" className="mt-6 inline-flex rounded-xl bg-[var(--primary)] px-5 py-3 text-sm font-medium text-[var(--background)]">Return to marketplace</Link></div></div>;
 const price=item.price==null?"Contact seller":`${item.currency_code||"USD"} ${item.price.toLocaleString()}`; const published=item.created_at?new Date(item.created_at):null;
 return <div className="mx-auto max-w-6xl px-4 py-7 sm:px-6 lg:px-8"><div className="flex items-center justify-between gap-4"><Link href="/marketplace" className="inline-flex items-center gap-2 text-sm font-medium text-[var(--muted)]"><ArrowLeft size={16}/> Marketplace</Link><button onClick={shareListing} className="inline-flex items-center gap-2 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 py-2 text-sm font-medium"><Share2 size={15}/> Share</button></div>
 <main className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1.35fr)_380px]"><section className="space-y-6"><div className="overflow-hidden rounded-[2rem] border border-[var(--border)] bg-[var(--surface)] shadow-[var(--shadow-sm)]"><div className="relative flex min-h-[330px] items-center justify-center bg-[var(--background)] sm:min-h-[480px]"><div className="text-center"><div className="mx-auto flex h-20 w-20 items-center justify-center rounded-3xl border border-[var(--border)] bg-[var(--surface)] shadow-[var(--shadow-sm)]"><ShoppingBag size={36} className="text-[var(--muted)]"/></div><p className="mt-4 text-sm font-medium">DRIGHT listing</p><p className="mt-1 text-xs text-[var(--muted)]">No listing media is exposed by the current marketplace record.</p></div><span className="absolute left-5 top-5 rounded-full border border-[var(--border)] bg-[var(--surface)]/90 px-3 py-1.5 text-xs font-semibold uppercase tracking-wide text-[var(--muted)] backdrop-blur">{labelFor(item.item_type)}</span></div><div className="p-6 sm:p-9"><div className="flex flex-wrap gap-2"><span className="inline-flex items-center gap-1 rounded-full border border-[var(--border)] bg-[var(--background)] px-3 py-1.5 text-xs font-semibold text-[var(--muted)]"><CheckCircle2 size={13}/> Published</span>{published&&<span className="inline-flex items-center gap-1 rounded-full border border-[var(--border)] px-3 py-1.5 text-xs text-[var(--muted)]"><Clock3 size={13}/> {published.toLocaleDateString()}</span>}</div><h1 className="mt-5 text-3xl font-semibold tracking-tight sm:text-4xl lg:text-[2.75rem] lg:leading-tight">{item.title}</h1><p className="mt-5 whitespace-pre-wrap text-base leading-7 text-[var(--muted)]">{item.description||"The seller has not added a description yet."}</p></div></div>
 <div className="rounded-[2rem] border border-[var(--border)] bg-[var(--surface)] p-6 shadow-[var(--shadow-sm)] sm:p-8"><div className="flex items-center gap-3"><Sparkles size={19}/><div><h2 className="font-semibold">Listing insights</h2><p className="text-xs text-[var(--muted)]">Verified metadata available from the current DRIGHT listing record.</p></div></div><dl className="mt-6 grid gap-4 sm:grid-cols-2"><div className="rounded-xl bg-[var(--background)] p-4"><dt className="text-xs text-[var(--muted)]">Listing type</dt><dd className="mt-1 font-medium">{labelFor(item.item_type)}</dd></div><div className="rounded-xl bg-[var(--background)] p-4"><dt className="text-xs text-[var(--muted)]">Currency</dt><dd className="mt-1 font-medium">{item.currency_code||"USD"}</dd></div><div className="rounded-xl bg-[var(--background)] p-4 sm:col-span-2"><dt className="text-xs text-[var(--muted)]">DRIGHT Listing ID</dt><dd className="mt-1 break-all font-mono text-sm">{item.id}</dd></div></dl><div className="mt-5 flex flex-wrap gap-2"><button onClick={copyId} className="inline-flex items-center gap-2 rounded-xl border border-[var(--border)] px-3 py-2.5 text-sm font-medium"><Copy size={15}/>{copied?"Copied":"Copy listing ID"}</button><button onClick={shareListing} className="inline-flex items-center gap-2 rounded-xl border border-[var(--border)] px-3 py-2.5 text-sm font-medium"><ExternalLink size={15}/> Share listing</button></div></div></section>
 <aside className="h-fit lg:sticky lg:top-24"><div className="rounded-[2rem] border border-[var(--border)] bg-[var(--surface)] p-6 shadow-[var(--shadow-md)] sm:p-7"><p className="text-sm text-[var(--muted)]">Current price</p><p className="mt-1 text-3xl font-semibold tracking-tight">{price}</p><p className="mt-2 text-xs text-[var(--muted)]">Pricing shown directly from the published listing record.</p><button onClick={addToCart} disabled={adding||item.price==null} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-[var(--primary)] px-5 py-3.5 text-sm font-semibold text-[var(--background)] disabled:opacity-50"><ShoppingBag size={17}/>{adding?"Adding…":added?"Added to cart":"Add to cart"}</button>{added&&<Link href="/cart" className="mt-3 flex w-full items-center justify-center rounded-xl border border-[var(--border)] px-5 py-3 text-sm font-semibold">View cart</Link>}{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}<div className="mt-3 rounded-xl border border-[var(--border)] bg-[var(--background)] p-4"><div className="flex items-center gap-2 text-sm font-semibold"><MessageCircle size={16}/> Seller contact</div><p className="mt-2 text-xs leading-5 text-[var(--muted)]">Seller identity and messaging are shown only when the current listing exposes an authorized seller association. This listing record does not currently expose one.</p></div></div><div className="mt-5 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><div className="flex items-center gap-3"><Sparkles size={18}/><h2 className="font-semibold">DRIGHT protection</h2></div><ul className="mt-4 space-y-3 text-sm leading-5 text-[var(--muted)]"><li>• Keep the Listing ID with your order or transaction ID for support.</li><li>• Eligible purchases can unlock supported entitlements.</li><li>• Affiliate attribution and commissions remain handled by DRIGHT commerce systems.</li></ul></div></aside></main></div>;
}
function labelFor(value:string|null){const labels:Record<string,string>={product:"Products",service:"Services",course:"Courses",job:"Jobs",task:"Tasks"};return labels[value||""]||value||"Listing"}
