"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { ArrowLeft, CheckCircle2, Clock3, Copy, ExternalLink, Heart, MessageCircle, Share2, ShoppingBag, Sparkles, Store } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Item = { id:string; title:string; description:string|null; item_type:string|null; price:number|null; currency_code:string|null; status:string|null; created_at:string|null; owner_user_id:string|null; store_id:string|null };
type StoreInfo = { id:string; name:string; slug:string|null; description:string|null; logo_url:string|null; is_verified:boolean|null; public_id:string|null };

export default function ListingDetailPage() {
 const params=useParams<{id:string}>(); const id=typeof params.id==="string"?params.id:""; const supabase=createClient();
 const [item,setItem]=useState<Item|null>(null); const [store,setStore]=useState<StoreInfo|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [copied,setCopied]=useState(false); const [adding,setAdding]=useState(false); const [added,setAdded]=useState(false); const [favorite,setFavorite]=useState(false); const [favoriteBusy,setFavoriteBusy]=useState(false);
 useEffect(()=>{ if(!id)return; (async()=>{setLoading(true);setError(""); const {data,error:e}=await supabase.from("marketplace_items").select("id,title,description,item_type,price,currency_code,status,created_at,owner_user_id,store_id").eq("id",id).eq("status","published").maybeSingle(); if(e){setError(e.message);setLoading(false);return} setItem(data as Item|null); if(data?.store_id){const s=await supabase.from("stores").select("id,name,slug,description,logo_url,is_verified,public_id").eq("id",data.store_id).maybeSingle(); if(!s.error&&s.data)setStore(s.data as StoreInfo)} const {data:{user}}=await supabase.auth.getUser(); if(user){const f=await supabase.from("marketplace_item_favorites").select("item_id").eq("user_id",user.id).eq("item_id",id).maybeSingle(); setFavorite(Boolean(f.data)); await supabase.from("recently_viewed_items").upsert({user_id:user.id,item_id:id,last_viewed_at:new Date().toISOString(),view_count:1},{onConflict:"user_id,item_id",ignoreDuplicates:false});} setLoading(false);})(); },[id]);
 async function copyId(){try{await navigator.clipboard?.writeText(id)}catch{}setCopied(true);window.setTimeout(()=>setCopied(false),1600)}
 async function shareListing(){const d={title:item?.title||"DRIGHT listing",text:"View this DRIGHT listing",url:window.location.href};if(navigator.share)await navigator.share(d).catch(()=>undefined);else await copyId()}
 async function toggleFavorite(){const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href=`/login?next=${encodeURIComponent(`/marketplace/${id}`)}`;return} setFavoriteBusy(true);setError(""); if(favorite){const r=await supabase.from("marketplace_item_favorites").delete().eq("user_id",user.id).eq("item_id",id);if(r.error)setError(r.error.message);else setFavorite(false)}else{const r=await supabase.from("marketplace_item_favorites").insert({user_id:user.id,item_id:id});if(r.error)setError(r.error.message);else setFavorite(true)} setFavoriteBusy(false)}
 async function addToCart(){setAdding(true);setError("");const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href=`/login?next=${encodeURIComponent(`/marketplace/${id}`)}`;return}let {data:cart,error:ce}=await supabase.from("carts").select("id").eq("user_id",user.id).maybeSingle();if(ce){setError(ce.message);setAdding(false);return}if(!cart){const created=await supabase.from("carts").insert({user_id:user.id}).select("id").single();if(created.error){setError(created.error.message);setAdding(false);return}cart=created.data}const existing=await supabase.from("cart_items").select("id,quantity").eq("cart_id",cart.id).eq("marketplace_item_id",id).maybeSingle();if(existing.error){setError(existing.error.message);setAdding(false);return}const price=item?.price??0,currency_code=item?.currency_code||"USD";const result=existing.data?await supabase.from("cart_items").update({quantity:existing.data.quantity+1,unit_price:price,currency_code}).eq("id",existing.data.id):await supabase.from("cart_items").insert({cart_id:cart.id,marketplace_item_id:id,quantity:1,unit_price:price,currency_code});if(result.error)setError(result.error.message);else setAdded(true);setAdding(false)}
 if(loading)return <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6"><div className="grid gap-6 lg:grid-cols-[minmax(0,1.35fr)_380px]"><div className="h-[520px] animate-pulse rounded-[2rem] border border-[var(--border)] bg-[var(--surface)]"/><div className="h-[430px] animate-pulse rounded-[2rem] border border-[var(--border)] bg-[var(--surface)]"/></div></div>;
 if(error&&!item)return <State title="Could not load this listing" text={error}/>;
 if(!item)return <State title="Listing not found" text="This listing may be unpublished or no longer available."/>;
 const price=item.price==null?"Contact seller":`${item.currency_code||"USD"} ${item.price.toLocaleString()}`; const published=item.created_at?new Date(item.created_at):null;
 return <div className="mx-auto max-w-6xl px-4 py-7 sm:px-6 lg:px-8"><div className="flex items-center justify-between gap-4"><Link href="/marketplace" className="inline-flex items-center gap-2 text-sm font-medium text-[var(--muted)]"><ArrowLeft size={16}/> Marketplace</Link><div className="flex gap-2"><button onClick={toggleFavorite} disabled={favoriteBusy} aria-label={favorite?"Remove from favorites":"Save listing"} className={`inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm font-medium ${favorite?"border-[var(--primary)] bg-[var(--primary)]/10":"border-[var(--border)] bg-[var(--surface)]"}`}><Heart size={15} fill={favorite?"currentColor":"none"}/><span className="hidden sm:inline">{favorite?"Saved":"Save"}</span></button><button onClick={shareListing} className="inline-flex items-center gap-2 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 py-2 text-sm font-medium"><Share2 size={15}/> <span className="hidden sm:inline">Share</span></button></div></div>
 <main className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1.35fr)_380px]"><section className="space-y-6"><div className="overflow-hidden rounded-[2rem] border border-[var(--border)] bg-[var(--surface)] shadow-[var(--shadow-sm)]"><div className="relative flex min-h-[330px] items-center justify-center bg-[var(--background)] sm:min-h-[480px]"><div className="text-center"><div className="mx-auto flex h-20 w-20 items-center justify-center rounded-3xl border border-[var(--border)] bg-[var(--surface)] shadow-[var(--shadow-sm)]"><ShoppingBag size={36} className="text-[var(--muted)]"/></div><p className="mt-4 text-sm font-medium">DRIGHT listing</p><p className="mt-1 text-xs text-[var(--muted)]">Listing media will appear here when exposed by the listing media system.</p></div><span className="absolute left-5 top-5 rounded-full border border-[var(--border)] bg-[var(--surface)]/90 px-3 py-1.5 text-xs font-semibold uppercase tracking-wide text-[var(--muted)] backdrop-blur">{labelFor(item.item_type)}</span></div><div className="p-6 sm:p-9"><div className="flex flex-wrap gap-2"><span className="inline-flex items-center gap-1 rounded-full border border-[var(--border)] bg-[var(--background)] px-3 py-1.5 text-xs font-semibold text-[var(--muted)]"><CheckCircle2 size={13}/> Published</span>{published&&<span className="inline-flex items-center gap-1 rounded-full border border-[var(--border)] px-3 py-1.5 text-xs text-[var(--muted)]"><Clock3 size={13}/> {published.toLocaleDateString()}</span>}</div><h1 className="mt-5 text-3xl font-semibold tracking-tight sm:text-4xl lg:text-[2.75rem] lg:leading-tight">{item.title}</h1><p className="mt-5 whitespace-pre-wrap text-base leading-7 text-[var(--muted)]">{item.description||"The seller has not added a description yet."}</p></div></div>
 {store&&<section className="rounded-[2rem] border border-[var(--border)] bg-[var(--surface)] p-6 shadow-[var(--shadow-sm)] sm:p-8"><div className="flex items-start gap-4"><div className="flex h-14 w-14 shrink-0 items-center justify-center overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--background)]">{store.logo_url?<img src={store.logo_url} alt="" className="h-full w-full object-cover"/>:<Store size={23} className="text-[var(--muted)]"/>}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold">{store.name}</h2>{store.is_verified&&<span className="rounded-full border border-[var(--border)] px-2 py-1 text-[10px] font-semibold">Verified store</span>}</div>{store.public_id&&<p className="mt-1 font-mono text-[10px] text-[var(--muted)]">Store ID: {store.public_id}</p>}<p className="mt-2 text-sm leading-6 text-[var(--muted)]">{store.description||"DRIGHT store"}</p></div></div><div className="mt-5 flex flex-wrap gap-2"><Link href={`/marketplace?store=${encodeURIComponent(store.id)}`} className="inline-flex items-center gap-2 rounded-xl border border-[var(--border)] px-3 py-2.5 text-sm font-medium"><Store size={15}/> View store listings</Link>{item.owner_user_id&&<Link href={`/profile/${item.owner_user_id}`} className="inline-flex items-center gap-2 rounded-xl border border-[var(--border)] px-3 py-2.5 text-sm font-medium">Seller profile</Link>}</div></section>}
 <div className="rounded-[2rem] border border-[var(--border)] bg-[var(--surface)] p-6 shadow-[var(--shadow-sm)] sm:p-8"><div className="flex items-center gap-3"><Sparkles size={19}/><div><h2 className="font-semibold">Listing insights</h2><p className="text-xs text-[var(--muted)]">Verified metadata available from DRIGHT.</p></div></div><dl className="mt-6 grid gap-4 sm:grid-cols-2"><Info label="Listing type" value={labelFor(item.item_type)}/><Info label="Currency" value={item.currency_code||"USD"}/><Info label="Seller ID" value={item.owner_user_id||"Not exposed"}/><Info label="Store ID" value={item.store_id||"Not applicable"}/><div className="rounded-xl bg-[var(--background)] p-4 sm:col-span-2"><dt className="text-xs text-[var(--muted)]">DRIGHT Listing ID</dt><dd className="mt-1 break-all font-mono text-sm">{item.id}</dd></div></dl><div className="mt-5 flex flex-wrap gap-2"><button onClick={copyId} className="inline-flex items-center gap-2 rounded-xl border border-[var(--border)] px-3 py-2.5 text-sm font-medium"><Copy size={15}/>{copied?"Copied":"Copy listing ID"}</button><button onClick={shareListing} className="inline-flex items-center gap-2 rounded-xl border border-[var(--border)] px-3 py-2.5 text-sm font-medium"><ExternalLink size={15}/> Share listing</button></div></div></section>
 <aside className="h-fit lg:sticky lg:top-24"><div className="rounded-[2rem] border border-[var(--border)] bg-[var(--surface)] p-6 shadow-[var(--shadow-md)] sm:p-7"><p className="text-sm text-[var(--muted)]">Current price</p><p className="mt-1 text-3xl font-semibold tracking-tight">{price}</p><p className="mt-2 text-xs text-[var(--muted)]">Pricing shown directly from the published listing record.</p><button onClick={addToCart} disabled={adding||item.price==null} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-[var(--primary)] px-5 py-3.5 text-sm font-semibold text-[var(--background)] disabled:opacity-50"><ShoppingBag size={17}/>{adding?"Adding…":added?"Added to cart":"Add to cart"}</button>{added&&<Link href="/cart" className="mt-3 flex w-full items-center justify-center rounded-xl border border-[var(--border)] px-5 py-3 text-sm font-semibold">View cart</Link>}{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}<div className="mt-3 rounded-xl border border-[var(--border)] bg-[var(--background)] p-4"><div className="flex items-center gap-2 text-sm font-semibold"><MessageCircle size={16}/> Seller contact</div><p className="mt-2 text-xs leading-5 text-[var(--muted)]">Use DRIGHT messaging for seller conversations. Direct private seller information is not exposed here.</p>{item.owner_user_id&&<Link href={`/messages/new?user=${encodeURIComponent(item.owner_user_id)}&listing=${encodeURIComponent(item.id)}`} className="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-xl border border-[var(--border)] px-3 py-2.5 text-sm font-medium"><MessageCircle size={15}/> Contact seller</Link>}</div></div><div className="mt-5 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><div className="flex items-center gap-3"><Sparkles size={18}/><h2 className="font-semibold">DRIGHT protection</h2></div><ul className="mt-4 space-y-3 text-sm leading-5 text-[var(--muted)]"><li>• Keep the Listing ID with your order or transaction ID for support.</li><li>• Eligible purchases can unlock supported entitlements.</li><li>• Affiliate attribution and commissions remain handled by DRIGHT commerce systems.</li></ul></div></aside></main></div>;
}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-[var(--background)] p-4"><dt className="text-xs text-[var(--muted)]">{label}</dt><dd className="mt-1 break-all font-medium text-sm">{value}</dd></div>}
function State({title,text}:{title:string;text:string}){return <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6"><Link href="/marketplace" className="inline-flex items-center gap-2 text-sm text-[var(--muted)]"><ArrowLeft size={16}/> Back</Link><div className="mt-6 rounded-[2rem] border border-dashed border-[var(--border)] bg-[var(--surface)] p-12 text-center"><ShoppingBag className="mx-auto" size={28}/><h1 className="mt-4 text-xl font-semibold">{title}</h1><p className="mt-2 text-sm text-[var(--muted)]">{text}</p><Link href="/marketplace" className="mt-6 inline-flex rounded-xl bg-[var(--primary)] px-5 py-3 text-sm font-medium text-[var(--background)]">Return to marketplace</Link></div></div>}
function labelFor(value:string|null){const labels:Record<string,string>={product:"Products",service:"Services",course:"Courses",job:"Jobs",task:"Tasks"};return labels[value||""]||value||"Listing"}
