"use client";

import { useEffect, useState } from "react";
import { Loader2, Palette, Save } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

export default function ThemesPage(){const supabase=createClient();const [themes,setThemes]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState<string|null>(null);const [error,setError]=useState("");
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href="/login?next=/admin/themes";return;}const {data:ok}=await supabase.rpc("admin_has_permission",{p_permission:"themes.manage",p_user_id:user.id});if(!ok){setError("You do not have permission to manage themes.");setLoading(false);return;}const {data,e}=await supabase.from("platform_theme_settings").select("id,theme_key,display_name,is_enabled,config").order("display_name");if(e)setError(e.message);setThemes(data||[]);setLoading(false);}
 useEffect(()=>{load();},[]);
 async function toggle(theme:any){setSaving(theme.id);const {data:{user}}=await supabase.auth.getUser();const {error:e}=await supabase.from("platform_theme_settings").update({is_enabled:!theme.is_enabled,updated_by:user?.id,updated_at:new Date().toISOString()}).eq("id",theme.id);if(e)setError(e.message);else setThemes(ts=>ts.map(t=>t.id===theme.id?{...t,is_enabled:!t.is_enabled}:t));setSaving(null);}
 if(error&&!themes.length&&!loading)return <main className="mx-auto max-w-xl px-4 py-16 text-center"><Palette className="mx-auto" size={40}/><h1 className="mt-4 text-2xl font-semibold">Access restricted</h1><p className="mt-2 text-sm text-[var(--muted)]">{error}</p></main>;
 return <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8"><p className="text-xs font-semibold uppercase tracking-widest text-[var(--muted)]">Governance · Design System</p><h1 className="mt-1 text-3xl font-semibold">Theme Administration</h1><p className="mt-2 text-sm text-[var(--muted)]">Control centralized DRIGHT theme availability without hard-coding theme choices into pages.</p>{error&&<p className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{loading?<div className="p-8 text-sm text-[var(--muted)]">Loading themes…</div>:themes.map(t=><div key={t.id} className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><div className="flex items-center justify-between"><div><p className="font-semibold">{t.display_name}</p><p className="mt-1 text-xs text-[var(--muted)]">{t.theme_key}</p></div><span className={`rounded-full px-2 py-1 text-[10px] uppercase ${t.is_enabled?"bg-[var(--primary)] text-[var(--background)]":"border border-[var(--border)] text-[var(--muted)]"}`}>{t.is_enabled?"enabled":"disabled"}</span></div><button onClick={()=>toggle(t)} disabled={saving===t.id} className="mt-5 inline-flex items-center gap-2 rounded-xl border border-[var(--border)] px-3 py-2 text-sm font-semibold">{saving===t.id?<Loader2 className="animate-spin" size={15}/>:<Save size={15}/>} {t.is_enabled?"Disable":"Enable"}</button></div>)}</section></main>;
}
