-- Phase L analytics foundation. The function is SECURITY INVOKER so existing RLS remains authoritative.
create or replace function public.get_analytics_snapshot(p_days integer default 30)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_days integer := greatest(1, least(coalesce(p_days,30),365));
  v_since timestamptz := now()-make_interval(days=>v_days);
  v_prev_since timestamptz := v_since-make_interval(days=>v_days);
  v_is_admin boolean := false; v_is_seller boolean := false; v_is_affiliate boolean := false; v_is_job_employer boolean := false;
  v_buyer jsonb:='{}'; v_seller jsonb:='{}'; v_affiliate jsonb:='{}'; v_referral jsonb:='{}'; v_jobs jsonb:='{}'; v_admin jsonb:='{}';
  v_order_count bigint:=0; v_spend numeric:=0; v_saved bigint:=0; v_activity bigint:=0; v_rec_count bigint:=0; v_seller_views bigint:=0; v_seller_clicks bigint:=0; v_seller_sales bigint:=0; v_seller_revenue numeric:=0; v_seller_products bigint:=0; v_seller_customers bigint:=0; v_aff_clicks bigint:=0; v_aff_conversions bigint:=0; v_commission numeric:=0; v_aff_earnings numeric:=0; v_ref_invites bigint:=0; v_ref_qualified bigint:=0; v_rewards numeric:=0; v_job_apps bigint:=0; v_job_active bigint:=0; v_users bigint:=0; v_sellers bigint:=0; v_buyers bigint:=0; v_transactions bigint:=0; v_revenue numeric:=0; v_mod_reports bigint:=0; v_support bigint:=0; v_fraud bigint:=0; v_ai_requests bigint:=0; v_ai_cost numeric:=0;
begin
  if v_user is null then return jsonb_build_object('authenticated',false,'days',v_days); end if;
  v_is_admin := public.is_super_admin(v_user) or public.has_permission('analytics.view',v_user);
  v_is_seller := exists(select 1 from public.user_roles ur join public.roles r on r.id=ur.role_id where ur.user_id=v_user and ur.status='active' and r.slug in ('vendor','job_employer'));
  v_is_affiliate := exists(select 1 from public.user_roles ur join public.roles r on r.id=ur.role_id where ur.user_id=v_user and ur.status='active' and r.slug='affiliate');
  v_is_job_employer := exists(select 1 from public.user_roles ur join public.roles r on r.id=ur.role_id where ur.user_id=v_user and ur.status='active' and r.slug='job_employer');
  select count(*) into v_order_count from public.orders where buyer_user_id=v_user and created_at>=v_since; select coalesce(sum(total),0) into v_spend from public.orders where buyer_user_id=v_user and created_at>=v_since and status in ('paid','processing','completed'); select count(*) into v_saved from public.marketplace_item_favorites where user_id=v_user; select count(*) into v_activity from public.discovery_events where user_id=v_user and created_at>=v_since; select count(*) into v_rec_count from public.recommendation_candidates where user_id=v_user and status='active' and (expires_at is null or expires_at>now()); v_buyer:=jsonb_build_object('purchases',v_order_count,'spending',v_spend,'saved_products',v_saved,'activity',v_activity,'recommendations',v_rec_count);
  if v_is_seller then select count(*) into v_seller_products from public.marketplace_items where owner_user_id=v_user; select count(*) into v_seller_views from public.discovery_events e where e.entity_id in(select id from public.marketplace_items where owner_user_id=v_user) and e.event_type in('impression','open') and e.created_at>=v_since; select count(*) into v_seller_clicks from public.discovery_events e where e.entity_id in(select id from public.marketplace_items where owner_user_id=v_user) and e.event_type='click' and e.created_at>=v_since; select count(*) into v_seller_sales from public.order_items oi where oi.seller_user_id=v_user and exists(select 1 from public.orders o where o.id=oi.order_id and o.status in('paid','processing','completed') and o.created_at>=v_since); select coalesce(sum(oi.unit_price*oi.quantity),0) into v_seller_revenue from public.order_items oi where oi.seller_user_id=v_user and exists(select 1 from public.orders o where o.id=oi.order_id and o.status in('paid','processing','completed') and o.created_at>=v_since); select count(distinct o.buyer_user_id) into v_seller_customers from public.orders o join public.order_items oi on oi.order_id=o.id where oi.seller_user_id=v_user and o.buyer_user_id is not null and o.created_at>=v_since and o.status in('paid','processing','completed'); v_seller:=jsonb_build_object('views',v_seller_views,'clicks',v_seller_clicks,'sales',v_seller_sales,'conversion',case when v_seller_views>0 then round(v_seller_sales::numeric/v_seller_views*100,2) else 0 end,'revenue',v_seller_revenue,'products',v_seller_products,'customers',v_seller_customers,'reviews',null,'traffic',v_seller_views,'campaign_performance',null); end if;
  if v_is_affiliate then select count(*) into v_aff_clicks from public.affiliate_clicks c join public.affiliate_links l on l.id=c.affiliate_link_id where l.affiliate_user_id=v_user and c.created_at>=v_since; select count(*) into v_aff_conversions from public.affiliate_attributions a join public.affiliate_links l on l.id=a.affiliate_link_id where l.affiliate_user_id=v_user and a.attribution_status='confirmed' and a.attributed_at>=v_since; select coalesce(sum(c.commission_amount),0) into v_commission from public.commissions c where c.affiliate_user_id=v_user and c.created_at>=v_since; select coalesce(sum(c.commission_amount) filter(where c.status in('available','paid')),0) into v_aff_earnings from public.commissions c where c.affiliate_user_id=v_user and c.created_at>=v_since; v_affiliate:=jsonb_build_object('clicks',v_aff_clicks,'conversions',v_aff_conversions,'commission',v_commission,'earnings',v_aff_earnings,'conversion_rate',case when v_aff_clicks>0 then round(v_aff_conversions::numeric/v_aff_clicks*100,2) else 0 end,'top_products',null); end if;
  select count(*) into v_ref_invites from public.referrals where referrer_user_id=v_user and created_at>=v_since; select count(*) into v_ref_qualified from public.referrals where referrer_user_id=v_user and status in('qualified','rewarded') and created_at>=v_since; select coalesce(sum(reward_amount),0) into v_rewards from public.referral_rewards where beneficiary_user_id=v_user and created_at>=v_since and status in('available','paid'); v_referral:=jsonb_build_object('invitations',v_ref_invites,'qualified_referrals',v_ref_qualified,'rewards',v_rewards,'conversion',case when v_ref_invites>0 then round(v_ref_qualified::numeric/v_ref_invites*100,2) else 0 end);
  if v_is_job_employer then select count(*) into v_job_active from public.jobs where employer_id=v_user and status='published'; select count(*) into v_job_apps from public.job_applications a join public.jobs j on j.id=a.job_id where j.employer_id=v_user and a.created_at>=v_since; v_jobs:=jsonb_build_object('views',null,'applications',v_job_apps,'conversion',null,'active_jobs',v_job_active); end if;
  if v_is_admin then select count(*) into v_users from public.profiles where created_at>=v_since; select count(*) into v_sellers from public.marketplace_items where created_at>=v_since; select count(distinct buyer_user_id) into v_buyers from public.orders where buyer_user_id is not null and created_at>=v_since; select count(*) into v_transactions from public.transactions where created_at>=v_since and status='successful'; select coalesce(sum(amount),0) into v_revenue from public.transactions where created_at>=v_since and status='successful'; select count(*) into v_mod_reports from public.reports where created_at>=v_since; select count(*) into v_support from public.crm_support_tickets where created_at>=v_since; select count(*) into v_fraud from public.refund_disputes where created_at>=v_since and reason_type in('fraud','payment_fraud','theft'); select count(*) into v_ai_requests from public.ai_usage where created_at>=v_since; select coalesce(sum(estimated_cost),0) into v_ai_cost from public.ai_usage where created_at>=v_since; v_admin:=jsonb_build_object('platform_growth',v_users,'users',v_users,'sellers',v_sellers,'buyers',v_buyers,'transactions',v_transactions,'revenue',v_revenue,'marketplace_performance',jsonb_build_object('listing_events',(select count(*) from public.discovery_events where created_at>=v_since)),'moderation',v_mod_reports,'support',v_support,'fraud',v_fraud,'ai_usage',jsonb_build_object('requests',v_ai_requests,'estimated_cost',v_ai_cost)); end if;
  return jsonb_build_object('authenticated',true,'days',v_days,'from',v_since,'comparison_from',v_prev_since,'buyer',v_buyer,'seller',v_seller,'affiliate',v_affiliate,'referral',v_referral,'jobs',v_jobs,'admin',v_admin,'permissions',jsonb_build_object('admin',v_is_admin,'seller',v_is_seller,'affiliate',v_is_affiliate,'job_employer',v_is_job_employer));
end; $$;
