-- DRIGHT Prompt 4B: coupons, reward wallets, tokens, vouchers, gift codes, giveaways and campaign rewards.
-- Forward-only and non-destructive. All structures use IF NOT EXISTS and existing financial tables remain authoritative.
create extension if not exists pgcrypto;

create table if not exists public.coupons (id uuid primary key default gen_random_uuid(), coupon_id text not null unique default next_universal_id('COUPON'), code text not null unique, coupon_type text not null check(coupon_type in('percentage','fixed')), discount_value numeric(18,6) not null check(discount_value>=0), currency_code text, minimum_order_value numeric(18,6) not null default 0, maximum_discount numeric(18,6), maximum_total_uses integer, maximum_uses_per_user integer not null default 1, total_uses integer not null default 0, starts_at timestamptz, expires_at timestamptz, status text not null default 'draft', eligible_listing_ids uuid[] not null default '{}', eligible_categories text[] not null default '{}', eligible_seller_ids uuid[] not null default '{}', eligible_user_roles text[] not null default '{}', eligible_countries text[] not null default '{}', campaign_id uuid references public.marketing_campaigns(id) on delete set null, first_order_only boolean not null default false, new_user_only boolean not null default false, subscription_rule jsonb not null default '{}', referral_rule jsonb not null default '{}', metadata jsonb not null default '{}', created_by uuid not null references auth.users(id) on delete restrict, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.coupon_redemptions (id uuid primary key default gen_random_uuid(), redemption_id text not null unique default next_universal_id('COUPON_REDEMPTION'), coupon_id uuid not null references public.coupons(id) on delete restrict, user_id uuid references auth.users(id) on delete set null, order_id uuid references public.orders(id) on delete set null, discount_amount numeric(18,6) not null check(discount_amount>=0), currency_code text not null, campaign_id uuid references public.marketing_campaigns(id) on delete set null, status text not null default 'applied', created_at timestamptz not null default now(), unique(coupon_id,order_id));
create table if not exists public.reward_wallets (id uuid primary key default gen_random_uuid(), reward_wallet_id text not null unique default next_universal_id('REWARD_WALLET'), user_id uuid not null unique references auth.users(id) on delete cascade, promotion_credit_balance numeric(18,6) not null default 0, promotion_token_balance numeric(18,6) not null default 0, status text not null default 'active', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.reward_transactions (id uuid primary key default gen_random_uuid(), reward_transaction_id text not null unique default next_universal_id('REWARD_TRANSACTION'), user_id uuid not null references auth.users(id) on delete cascade, reward_type text not null, transaction_type text not null, amount numeric(18,6) not null check(amount>0), currency_code text, reason text, source_type text, source_id text, campaign_id uuid references public.marketing_campaigns(id) on delete set null, promotion_id uuid references public.marketing_campaigns(id) on delete set null, order_id uuid references public.orders(id) on delete set null, expires_at timestamptz, metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table if not exists public.vouchers (id uuid primary key default gen_random_uuid(), voucher_id text not null unique default next_universal_id('VOUCHER'), user_id uuid not null references auth.users(id) on delete cascade, voucher_type text not null, value numeric(18,6) not null, currency_code text, restrictions jsonb not null default '{}', source_type text, source_id text, campaign_id uuid references public.marketing_campaigns(id) on delete set null, status text not null default 'available', issued_at timestamptz not null default now(), expires_at timestamptz, redeemed_at timestamptz);
create table if not exists public.gift_codes (id uuid primary key default gen_random_uuid(), gift_code_id text not null unique default next_universal_id('GIFT_CODE'), code_hash text not null unique, code_last4 text not null, value numeric(18,6) not null, currency_code text not null, maximum_redemptions integer not null default 1, redemption_count integer not null default 0, eligible_user_ids uuid[] not null default '{}', campaign_id uuid references public.marketing_campaigns(id) on delete set null, status text not null default 'active', issued_at timestamptz not null default now(), expires_at timestamptz, created_by uuid not null references auth.users(id) on delete restrict, metadata jsonb not null default '{}');
create table if not exists public.gift_code_redemptions (id uuid primary key default gen_random_uuid(), gift_code_id uuid not null references public.gift_codes(id) on delete restrict, redemption_id text not null unique default next_universal_id('GIFT_REDEMPTION'), user_id uuid not null references auth.users(id) on delete restrict, redeemed_at timestamptz not null default now(), unique(gift_code_id,user_id));
create table if not exists public.giveaway_campaigns (id uuid primary key default gen_random_uuid(), giveaway_id text not null unique default next_universal_id('GIVEAWAY'), title text not null, description text, reward jsonb not null default '{}', entry_requirements jsonb not null default '{}', eligibility jsonb not null default '{}', max_entries integer, start_at timestamptz not null, end_at timestamptz not null, status text not null default 'draft', winner_user_id uuid references auth.users(id) on delete set null, winner_selected_at timestamptz, eligible_participant_count integer, selection_audit jsonb not null default '{}', campaign_id uuid references public.marketing_campaigns(id) on delete set null, created_by uuid not null references auth.users(id) on delete restrict, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.giveaway_entries (id uuid primary key default gen_random_uuid(), entry_id text not null unique default next_universal_id('GIVEAWAY_ENTRY'), giveaway_id uuid not null references public.giveaway_campaigns(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, qualification_snapshot jsonb not null default '{}', created_at timestamptz not null default now(), unique(giveaway_id,user_id));
create table if not exists public.reward_rules (id uuid primary key default gen_random_uuid(), rule_id text not null unique default next_universal_id('REWARD_RULE'), name text not null, event_key text not null, reward_type text not null, reward_amount numeric(18,6) not null, currency_code text, max_rewards integer, user_limit integer not null default 1, expiration_period interval, eligibility jsonb not null default '{}', campaign_id uuid references public.marketing_campaigns(id) on delete set null, enabled boolean not null default false, created_by uuid not null references auth.users(id) on delete restrict, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.campaign_rewards (id uuid primary key default gen_random_uuid(), reward_issuance_id text not null unique default next_universal_id('REWARD_ISSUANCE'), campaign_id uuid not null references public.marketing_campaigns(id) on delete cascade, reward_rule_id uuid references public.reward_rules(id) on delete set null, user_id uuid not null references auth.users(id) on delete cascade, reward_type text not null, amount numeric(18,6) not null, currency_code text, status text not null default 'issued', issued_at timestamptz not null default now(), expires_at timestamptz, unique(campaign_id,user_id,reward_rule_id));

create index if not exists idx_coupons_code_status on public.coupons(code,status); create index if not exists idx_coupons_dates on public.coupons(starts_at,expires_at); create index if not exists idx_coupon_redemptions_user on public.coupon_redemptions(user_id,created_at desc); create index if not exists idx_reward_transactions_user on public.reward_transactions(user_id,created_at desc); create index if not exists idx_vouchers_user_status on public.vouchers(user_id,status,expires_at); create index if not exists idx_gift_codes_status on public.gift_codes(status,expires_at); create index if not exists idx_giveaways_status_dates on public.giveaway_campaigns(status,start_at,end_at); create index if not exists idx_giveaway_entries_user on public.giveaway_entries(user_id,created_at desc); create index if not exists idx_reward_rules_event on public.reward_rules(event_key,enabled); create index if not exists idx_campaign_rewards_user on public.campaign_rewards(user_id,issued_at desc);

alter table public.coupons enable row level security; alter table public.coupon_redemptions enable row level security; alter table public.reward_wallets enable row level security; alter table public.reward_transactions enable row level security; alter table public.vouchers enable row level security; alter table public.gift_codes enable row level security; alter table public.gift_code_redemptions enable row level security; alter table public.giveaway_campaigns enable row level security; alter table public.giveaway_entries enable row level security; alter table public.reward_rules enable row level security; alter table public.campaign_rewards enable row level security;

-- Policies/functions are installed by the live forward migration used for this phase; this file records the same additive schema for reproducible environments.
